function out1 = ddx_sharm_C_6_0(x,y,z)
%DDX_SHARM_C_6_0
%    OUT1 = DDX_SHARM_C_6_0(X,Y,Z)

%    This function was generated by the Symbolic Math Toolbox version 6.3.
%    09-Jan-2017 14:53:25

t2 = x.^2;
t3 = y.^2;
t4 = z.^2;
t5 = t2.^2;
out1 = t5.*x.*-1.875-t3.^2.*x.*1.875-t4.^2.*x.*1.5e1-t2.*t3.*x.*3.75+t2.*t4.*x.*2.25e1+t3.*t4.*x.*2.25e1;
