function out1 = ddx_sharm_S_9_5(x,y,z)
%DDX_SHARM_S_9_5
%    OUT1 = DDX_SHARM_S_9_5(X,Y,Z)

%    This function was generated by the Symbolic Math Toolbox version 6.3.
%    09-Jan-2017 14:54:01

t2 = x.^2;
t3 = y.^2;
t4 = t3.^2;
t5 = t2.^2;
t6 = z.^2;
t7 = t6.^2;
out1 = t2.*t4.*x.*y.*-2.219638906444019e1+t2.*t5.*x.*y.*1.585456361745728e1-t3.*t4.*x.*y.*6.341825446982911+t2.*t7.*x.*y.*4.439277812888038e2-t3.*t7.*x.*y.*4.439277812888038e2+t4.*t6.*x.*y.*1.997675015799617e2-t5.*t6.*x.*y.*3.329458359666028e2+t2.*t3.*t6.*x.*y.*2.219638906444019e2;
