function out1 = ddx_sharm_S_9_2(x,y,z)
%DDX_SHARM_S_9_2
%    OUT1 = DDX_SHARM_S_9_2(X,Y,Z)

%    This function was generated by the Symbolic Math Toolbox version 6.3.
%    09-Jan-2017 14:53:57

t2 = y.^2;
t3 = z.^2;
t4 = t3.^2;
t5 = t2.^2;
t6 = x.^2;
t7 = t6.^2;
out1 = t2.*t4.*y.*z.*-1.101249290578659e2-t2.*t5.*y.*z.*6.88280806611662+t3.*t4.*y.*z.*3.146426544510455e1+t3.*t5.*y.*z.*6.88280806611662e1-t2.*t7.*y.*z.*1.032421209917493e2+t3.*t7.*y.*z.*3.44140403305831e2-t4.*t6.*y.*z.*3.303747871735977e2-t5.*t6.*y.*z.*6.194527259504958e1-t6.*t7.*y.*z.*4.817965646281634e1+t2.*t3.*t6.*y.*z.*4.129684839669972e2;
