function out1 = ddx_sharm_S_7_2(x,y,z)
%DDX_SHARM_S_7_2
%    OUT1 = DDX_SHARM_S_7_2(X,Y,Z)

%    This function was generated by the Symbolic Math Toolbox version 6.3.
%    09-Jan-2017 14:53:36

t2 = y.^2;
t3 = z.^2;
t4 = t3.^2;
t5 = t2.^2;
t6 = x.^2;
out1 = t6.^2.*y.*z.*3.037847202378684e1+t4.*y.*z.*1.944222209522358e1+t5.*y.*z.*6.075694404757369-t2.*t3.*y.*z.*3.24037034920393e1+t2.*t6.*y.*z.*3.645416642854421e1-t3.*t6.*y.*z.*9.72111104761179e1;
