function out1 = ddx_sharm_C_2_1(x,y,z)
%DDX_SHARM_C_2_1
%    OUT1 = DDX_SHARM_C_2_1(X,Y,Z)

%    This function was generated by the Symbolic Math Toolbox version 6.3.
%    09-Jan-2017 14:53:09

out1 = z.*1.732050807568877;
