function out1 = ddx_sharm_S_9_6(x,y,z)
%DDX_SHARM_S_9_6
%    OUT1 = DDX_SHARM_S_9_6(X,Y,Z)

%    This function was generated by the Symbolic Math Toolbox version 6.3.
%    09-Jan-2017 14:54:02

t2 = y.^2;
t3 = t2.^2;
t4 = z.^2;
t5 = x.^2;
t6 = t5.^2;
out1 = t2.*t3.*y.*z.*-1.842133825553941e1+t3.*t4.*y.*z.*8.596624519251727e1+t2.*t6.*y.*z.*2.149156129812932e2+t3.*t5.*y.*z.*1.289493677887759e2+t4.*t6.*y.*z.*4.298312259625863e2-t5.*t6.*y.*z.*1.289493677887759e2-t2.*t4.*t5.*y.*z.*8.596624519251727e2;
