function out1 = ddx_sharm_S_9_9(x,y,z)
%DDX_SHARM_S_9_9
%    OUT1 = DDX_SHARM_S_9_9(X,Y,Z)

%    This function was generated by the Symbolic Math Toolbox version 6.3.
%    09-Jan-2017 14:54:06

t2 = x.^2;
t3 = y.^2;
t4 = t3.^2;
t5 = t2.^2;
out1 = t2.*t4.*x.*y.*3.06960893656464e2+t2.*t5.*x.*y.*4.385155623663771e1-t3.*t4.*x.*y.*4.385155623663771e1-t3.*t5.*x.*y.*3.06960893656464e2;
