function out1 = ddx_sharm_C_1_1(x,y,z)
%DDX_SHARM_C_1_1
%    OUT1 = DDX_SHARM_C_1_1(X,Y,Z)

%    This function was generated by the Symbolic Math Toolbox version 6.3.
%    09-Jan-2017 14:53:07

out1 = 1.0;
