function out1 = ddx_sharm_S_9_7(x,y,z)
%DDX_SHARM_S_9_7
%    OUT1 = DDX_SHARM_S_9_7(X,Y,Z)

%    This function was generated by the Symbolic Math Toolbox version 6.3.
%    09-Jan-2017 14:54:03

t2 = x.^2;
t3 = y.^2;
t4 = t3.^2;
t5 = t2.^2;
t6 = z.^2;
out1 = t2.*t4.*x.*y.*2.481631740156061e1-t2.*t5.*x.*y.*2.481631740156061e1-t3.*t4.*x.*y.*1.772594100111472e1+t3.*t5.*x.*y.*7.444895220468183e1+t4.*t6.*x.*y.*2.977958088187273e2+t5.*t6.*x.*y.*2.977958088187273e2-t2.*t3.*t6.*x.*y.*9.926526960624244e2;
