function out1 = ddx_sharm_C_7_7(x,y,z)
%DDX_SHARM_C_7_7
%    OUT1 = DDX_SHARM_C_7_7(X,Y,Z)

%    This function was generated by the Symbolic Math Toolbox version 6.3.
%    09-Jan-2017 14:53:42

t2 = y.^2;
t3 = x.^2;
t4 = t3.^2;
t5 = t2.^2;
out1 = t2.*t4.*-6.796228417521368e1-t2.*t5.*4.530818945014245+t3.*t4.*4.530818945014245+t3.*t5.*6.796228417521368e1;
