function out1 = ddx_sharm_C_7_6(x,y,z)
%DDX_SHARM_C_7_6
%    OUT1 = DDX_SHARM_C_7_6(X,Y,Z)

%    This function was generated by the Symbolic Math Toolbox version 6.3.
%    09-Jan-2017 14:53:41

t2 = x.^2;
t3 = t2.^2;
t4 = y.^2;
out1 = t4.^2.*x.*z.*7.265473788749085e1+t3.*x.*z.*1.453094757749817e1-t2.*t4.*x.*z.*1.453094757749817e2;
