function out1 = ddx_sharm_S_4_2(x,y,z)
%DDX_SHARM_S_4_2
%    OUT1 = DDX_SHARM_S_4_2(X,Y,Z)

%    This function was generated by the Symbolic Math Toolbox version 6.3.
%    09-Jan-2017 14:53:16

t2 = y.^2;
out1 = t2.*y.*-1.118033988749895-x.^2.*y.*3.354101966249685+y.*z.^2.*6.708203932499369;
