function out1 = ddx_sharm_C_6_2(x,y,z)
%DDX_SHARM_C_6_2
%    OUT1 = DDX_SHARM_C_6_2(X,Y,Z)

%    This function was generated by the Symbolic Math Toolbox version 6.3.
%    09-Jan-2017 14:53:27

t2 = x.^2;
t3 = y.^2;
t4 = z.^2;
t5 = t2.^2;
out1 = t5.*x.*2.71713313991052-t3.^2.*x.*9.057110466368399e-1+t4.^2.*x.*1.449137674618944e1+t2.*t3.*x.*1.81142209327368-t2.*t4.*x.*2.898275349237888e1;
