function out1 = ddx_sharm_S_5_4(x,y,z)
%DDX_SHARM_S_5_4
%    OUT1 = DDX_SHARM_S_5_4(X,Y,Z)

%    This function was generated by the Symbolic Math Toolbox version 6.3.
%    09-Jan-2017 14:53:23

t2 = y.^2;
out1 = x.^2.*y.*z.*2.662235902394827e1-t2.*y.*z.*8.874119674649425;
