function out1 = ddx_sharm_C_8_4(x,y,z)
%DDX_SHARM_C_8_4
%    OUT1 = DDX_SHARM_C_8_4(X,Y,Z)

%    This function was generated by the Symbolic Math Toolbox version 6.3.
%    09-Jan-2017 14:53:48

t2 = x.^2;
t3 = y.^2;
t4 = t2.^2;
t5 = z.^2;
t6 = t3.^2;
t7 = t5.^2;
out1 = t2.*t4.*x.*3.290611645272046-t3.*t4.*x.*9.871834935816137-t2.*t6.*x.*1.645305822636023e1+t2.*t7.*x.*6.581223290544092e1-t3.*t6.*x.*3.290611645272046-t4.*t5.*x.*5.923100961489682e1-t3.*t7.*x.*1.974366987163227e2+t5.*t6.*x.*9.871834935816137e1+t2.*t3.*t5.*x.*1.974366987163227e2;
