function out1 = ddx_sharm_C_6_3(x,y,z)
%DDX_SHARM_C_6_3
%    OUT1 = DDX_SHARM_C_6_3(X,Y,Z)

%    This function was generated by the Symbolic Math Toolbox version 6.3.
%    09-Jan-2017 14:53:28

t2 = z.^2;
t3 = x.^2;
t4 = y.^2;
out1 = t3.^2.*z.*-1.35856656995526e1+t4.^2.*z.*8.151399419731559+t2.*t3.*z.*2.173706511928416e1-t2.*t4.*z.*2.173706511928416e1+t3.*t4.*z.*1.630279883946312e1;
