function out1 = ddx_sharm_C_7_3(x,y,z)
%DDX_SHARM_C_7_3
%    OUT1 = DDX_SHARM_C_7_3(X,Y,Z)

%    This function was generated by the Symbolic Math Toolbox version 6.3.
%    09-Jan-2017 14:53:37

t2 = y.^2;
t3 = x.^2;
t4 = z.^2;
t5 = t3.^2;
t6 = t4.^2;
t7 = t2.^2;
out1 = t2.*t5.*-2.14808235701055-t2.*t6.*3.43693177121688e1+t3.*t5.*3.00731529981477-t2.*t7.*1.28884941420633+t3.*t6.*3.43693177121688e1-t4.*t5.*4.2961647140211e1-t3.*t7.*6.44424707103165+t4.*t7.*2.57769882841266e1+t2.*t3.*t4.*5.15539765682532e1;
