function out1 = ddx_sharm_C_8_2(x,y,z)
%DDX_SHARM_C_8_2
%    OUT1 = DDX_SHARM_C_8_2(X,Y,Z)

%    This function was generated by the Symbolic Math Toolbox version 6.3.
%    09-Jan-2017 14:53:45

t2 = x.^2;
t3 = t2.^2;
t4 = z.^2;
t5 = y.^2;
t6 = t5.^2;
t7 = t4.^2;
out1 = t2.*t3.*x.*-3.137475099502783+t3.*t4.*x.*7.059318973881262e1-t3.*t5.*x.*4.706212649254175-t2.*t7.*x.*1.254990039801113e2-t4.*t6.*x.*2.353106324627087e1+t4.*t7.*x.*2.509980079602227e1+t5.*t6.*x.*1.568737549751392+t2.*t4.*t5.*x.*4.706212649254175e1;
