function out1 = ddx_sharm_C_9_6(x,y,z)
%DDX_SHARM_C_9_6
%    OUT1 = DDX_SHARM_C_9_6(X,Y,Z)

%    This function was generated by the Symbolic Math Toolbox version 6.3.
%    09-Jan-2017 14:54:02

t2 = x.^2;
t3 = t2.^2;
t4 = z.^2;
t5 = y.^2;
t6 = t5.^2;
out1 = t2.*t3.*x.*z.*-2.456178434071922e1+t3.*t4.*x.*z.*8.596624519251727e1+t3.*t5.*x.*z.*2.578987355775518e2+t4.*t6.*x.*z.*4.298312259625863e2-t5.*t6.*x.*z.*8.596624519251727e1-t2.*t4.*t5.*x.*z.*8.596624519251727e2;
