function out1 = ddx_sharm_S_6_5(x,y,z)
%DDX_SHARM_S_6_5
%    OUT1 = DDX_SHARM_S_6_5(X,Y,Z)

%    This function was generated by the Symbolic Math Toolbox version 6.3.
%    09-Jan-2017 14:53:31

t2 = y.^2;
t3 = x.^2;
out1 = t2.*x.*y.*z.*-4.653627617246571e1+t3.*x.*y.*z.*4.653627617246571e1;
