function out1 = ddx_sharm_S_9_1(x,y,z)
%DDX_SHARM_S_9_1
%    OUT1 = DDX_SHARM_S_9_1(X,Y,Z)

%    This function was generated by the Symbolic Math Toolbox version 6.3.
%    09-Jan-2017 14:53:55

t2 = x.^2;
t3 = y.^2;
t4 = t3.^2;
t5 = t2.^2;
t6 = z.^2;
t7 = t6.^2;
out1 = t2.*t4.*x.*y.*8.804517661405422+t2.*t5.*x.*y.*2.934839220468474+t3.*t4.*x.*y.*2.934839220468474+t3.*t5.*x.*y.*8.804517661405422+t2.*t7.*x.*y.*2.347871376374779e2+t3.*t7.*x.*y.*2.347871376374779e2-t4.*t6.*x.*y.*8.804517661405422e1-t5.*t6.*x.*y.*8.804517661405422e1-t6.*t7.*x.*y.*9.391485505499117e1-t2.*t3.*t6.*x.*y.*1.760903532281084e2;
