function out1 = ddx_sharm_S_4_3(x,y,z)
%DDX_SHARM_S_4_3
%    OUT1 = DDX_SHARM_S_4_3(X,Y,Z)

%    This function was generated by the Symbolic Math Toolbox version 6.3.
%    09-Jan-2017 14:53:17

out1 = x.*y.*z.*1.254990039801113e1;
