function out1 = ddx_sharm_C_4_0(x,y,z)
%DDX_SHARM_C_4_0
%    OUT1 = DDX_SHARM_C_4_0(X,Y,Z)

%    This function was generated by the Symbolic Math Toolbox version 6.3.
%    09-Jan-2017 14:53:14

t2 = x.^2;
out1 = t2.*x.*1.5+x.*y.^2.*1.5-x.*z.^2.*6.0;
