function out1 = ddx_sharm_C_5_5(x,y,z)
%DDX_SHARM_C_5_5
%    OUT1 = DDX_SHARM_C_5_5(X,Y,Z)

%    This function was generated by the Symbolic Math Toolbox version 6.3.
%    09-Jan-2017 14:53:24

t2 = x.^2;
t3 = y.^2;
out1 = t2.*t3.*-2.104682280060342e1+t2.^2.*3.50780380010057+t3.^2.*3.50780380010057;
