function out1 = ddx_sharm_S_3_1(x,y,z)
%DDX_SHARM_S_3_1
%    OUT1 = DDX_SHARM_S_3_1(X,Y,Z)

%    This function was generated by the Symbolic Math Toolbox version 6.3.
%    09-Jan-2017 14:53:11

out1 = x.*y.*-1.224744871391589;
