function out1 = ddx_sharm_C_4_2(x,y,z)
%DDX_SHARM_C_4_2
%    OUT1 = DDX_SHARM_C_4_2(X,Y,Z)

%    This function was generated by the Symbolic Math Toolbox version 6.3.
%    09-Jan-2017 14:53:15

t2 = x.^2;
out1 = t2.*x.*-2.23606797749979+x.*z.^2.*6.708203932499369;
