function out1 = ddx_sharm_S_7_1(x,y,z)
%DDX_SHARM_S_7_1
%    OUT1 = DDX_SHARM_S_7_1(X,Y,Z)

%    This function was generated by the Symbolic Math Toolbox version 6.3.
%    09-Jan-2017 14:53:34

t2 = x.^2;
t3 = y.^2;
t4 = t3.^2;
t5 = t2.^2;
t6 = z.^2;
out1 = t6.^2.*x.*y.*-3.968626966596886e1-t4.*x.*y.*2.480391854123054-t5.*x.*y.*2.480391854123054-t2.*t3.*x.*y.*4.960783708246107+t2.*t6.*x.*y.*3.968626966596886e1+t3.*t6.*x.*y.*3.968626966596886e1;
