function out1 = ddx_sharm_C_3_0(x,y,z)
%DDX_SHARM_C_3_0
%    OUT1 = DDX_SHARM_C_3_0(X,Y,Z)

%    This function was generated by the Symbolic Math Toolbox version 6.3.
%    09-Jan-2017 14:53:10

out1 = x.*z.*-3.0;
