function out1 = ddx_sharm_C_7_4(x,y,z)
%DDX_SHARM_C_7_4
%    OUT1 = DDX_SHARM_C_7_4(X,Y,Z)

%    This function was generated by the Symbolic Math Toolbox version 6.3.
%    09-Jan-2017 14:53:38

t2 = x.^2;
t3 = z.^2;
t4 = t2.^2;
t5 = y.^2;
out1 = t5.^2.*x.*z.*2.8497532787945e1-t4.*x.*z.*1.7098519672767e1+t2.*t3.*x.*z.*3.799671038392666e1+t2.*t5.*x.*z.*5.699506557588999e1-t3.*t5.*x.*z.*1.1399013115178e2;
