function out1 = ddx_sharm_S_3_3(x,y,z)
%DDX_SHARM_S_3_3
%    OUT1 = DDX_SHARM_S_3_3(X,Y,Z)

%    This function was generated by the Symbolic Math Toolbox version 6.3.
%    09-Jan-2017 14:53:13

out1 = x.*y.*4.743416490252569;
