function out1 = ddx_sharm_S_4_4(x,y,z)
%DDX_SHARM_S_4_4
%    OUT1 = DDX_SHARM_S_4_4(X,Y,Z)

%    This function was generated by the Symbolic Math Toolbox version 6.3.
%    09-Jan-2017 14:53:18

t2 = y.^2;
out1 = t2.*y.*-2.958039891549808+x.^2.*y.*8.874119674649424;
