function out1 = ddx_sharm_C_0_0(x,y,z)
%DDX_SHARM_C_0_0
%    OUT1 = DDX_SHARM_C_0_0(X,Y,Z)

%    This function was generated by the Symbolic Math Toolbox version 6.3.
%    09-Jan-2017 14:53:06

out1 = 0.0;
