function out1 = ddx_sharm_C_8_1(x,y,z)
%DDX_SHARM_C_8_1
%    OUT1 = DDX_SHARM_C_8_1(X,Y,Z)

%    This function was generated by the Symbolic Math Toolbox version 6.3.
%    09-Jan-2017 14:53:44

t2 = z.^2;
t3 = t2.^2;
t4 = x.^2;
t5 = y.^2;
t6 = t4.^2;
t7 = t5.^2;
out1 = t2.*t3.*z.*6.0-t3.*t4.*z.*9.45e1+t2.*t6.*z.*1.3125e2-t3.*t5.*z.*3.15e1+t2.*t7.*z.*2.625e1-t4.*t6.*z.*2.296875e1-t4.*t7.*z.*2.953125e1-t5.*t6.*z.*4.921875e1-t5.*t7.*z.*3.28125+t2.*t4.*t5.*z.*1.575e2;
