function out1 = ddx_sharm_C_9_4(x,y,z)
%DDX_SHARM_C_9_4
%    OUT1 = DDX_SHARM_C_9_4(X,Y,Z)

%    This function was generated by the Symbolic Math Toolbox version 6.3.
%    09-Jan-2017 14:53:59

t2 = x.^2;
t3 = z.^2;
t4 = t3.^2;
t5 = t2.^2;
t6 = y.^2;
t7 = t6.^2;
out1 = t2.*t4.*x.*z.*1.06119036934944e2+t2.*t5.*x.*z.*2.652975923373599e1-t3.*t5.*x.*z.*1.591785554024159e2-t2.*t7.*x.*z.*1.326487961686799e2+t3.*t7.*x.*z.*2.652975923373599e2-t4.*t6.*x.*z.*3.183571108048319e2-t5.*t6.*x.*z.*7.958927770120797e1-t6.*t7.*x.*z.*2.652975923373599e1+t2.*t3.*t6.*x.*z.*5.305951846747198e2;
