function out1 = ddx_sharm_C_5_1(x,y,z)
%DDX_SHARM_C_5_1
%    OUT1 = DDX_SHARM_C_5_1(X,Y,Z)

%    This function was generated by the Symbolic Math Toolbox version 6.3.
%    09-Jan-2017 14:53:19

t2 = x.^2;
t3 = y.^2;
t4 = z.^2;
out1 = t2.*t3.*2.904737509655563-t2.*t4.*1.742842505793338e1-t3.*t4.*5.809475019311125+t2.^2.*2.420614591379636+t3.^2.*4.841229182759271e-1+t4.^2.*3.872983346207417;
