function out1 = ddx_sharm_S_3_2(x,y,z)
%DDX_SHARM_S_3_2
%    OUT1 = DDX_SHARM_S_3_2(X,Y,Z)

%    This function was generated by the Symbolic Math Toolbox version 6.3.
%    09-Jan-2017 14:53:12

out1 = y.*z.*3.872983346207417;
