function out1 = ddy_sharm_S_8_3(x,y,z)
%DDY_SHARM_S_8_3
%    OUT1 = DDY_SHARM_S_8_3(X,Y,Z)

%    This function was generated by the Symbolic Math Toolbox version 6.3.
%    09-Jan-2017 14:53:47

t2 = z.^2;
t3 = t2.^2;
t4 = x.^2;
t5 = y.^2;
t6 = t4.^2;
t7 = t5.^2;
out1 = t3.*t4.*z.*5.097793640389929e1-t2.*t6.*z.*6.372242050487411e1-t3.*t5.*z.*5.097793640389929e1+t2.*t7.*z.*1.062040341747902e2+t4.*t6.*z.*9.558363075731116+t4.*t7.*z.*1.593060512621853e1+t5.*t6.*z.*4.779181537865558e1-t5.*t7.*z.*2.230284717670594e1-t2.*t4.*t5.*z.*1.274448410097482e2;
