function out1 = ddy_sharm_S_1_1(x,y,z)
%DDY_SHARM_S_1_1
%    OUT1 = DDY_SHARM_S_1_1(X,Y,Z)

%    This function was generated by the Symbolic Math Toolbox version 6.3.
%    09-Jan-2017 14:53:08

out1 = 1.0;
