function out1 = ddy_sharm_S_4_3(x,y,z)
%DDY_SHARM_S_4_3
%    OUT1 = DDY_SHARM_S_4_3(X,Y,Z)

%    This function was generated by the Symbolic Math Toolbox version 6.3.
%    09-Jan-2017 14:53:17

out1 = x.^2.*z.*6.274950199005567-y.^2.*z.*6.274950199005567;
