function out1 = ddy_sharm_S_9_9(x,y,z)
%DDY_SHARM_S_9_9
%    OUT1 = DDY_SHARM_S_9_9(X,Y,Z)

%    This function was generated by the Symbolic Math Toolbox version 6.3.
%    09-Jan-2017 14:54:06

t2 = y.^2;
t3 = t2.^2;
t4 = x.^2;
t5 = t4.^2;
out1 = t3.*t5.*3.837011170705799e2+t3.^2.*5.481444529579714+t5.^2.*5.481444529579714-t2.*t3.*t4.*1.53480446828232e2-t2.*t4.*t5.*1.53480446828232e2;
