function out1 = ddy_sharm_C_4_1(x,y,z)
%DDY_SHARM_C_4_1
%    OUT1 = DDY_SHARM_C_4_1(X,Y,Z)

%    This function was generated by the Symbolic Math Toolbox version 6.3.
%    09-Jan-2017 14:53:14

out1 = x.*y.*z.*-4.743416490252569;
