function out1 = ddy_sharm_C_3_3(x,y,z)
%DDY_SHARM_C_3_3
%    OUT1 = DDY_SHARM_C_3_3(X,Y,Z)

%    This function was generated by the Symbolic Math Toolbox version 6.3.
%    09-Jan-2017 14:53:13

out1 = x.*y.*-4.743416490252569;
