function out1 = ddy_sharm_S_5_3(x,y,z)
%DDY_SHARM_S_5_3
%    OUT1 = DDY_SHARM_S_5_3(X,Y,Z)

%    This function was generated by the Symbolic Math Toolbox version 6.3.
%    09-Jan-2017 14:53:22

t2 = x.^2;
t3 = y.^2;
t4 = z.^2;
out1 = t2.*t3.*-3.137475099502783+t2.*t4.*1.254990039801113e1-t3.*t4.*1.254990039801113e1-t2.^2.*1.568737549751392+t3.^2.*2.614562582918986;
