function out1 = ddy_sharm_S_4_4(x,y,z)
%DDY_SHARM_S_4_4
%    OUT1 = DDY_SHARM_S_4_4(X,Y,Z)

%    This function was generated by the Symbolic Math Toolbox version 6.3.
%    09-Jan-2017 14:53:18

t2 = x.^2;
out1 = t2.*x.*2.958039891549808-x.*y.^2.*8.874119674649424;
