function out1 = ddy_sharm_S_8_8(x,y,z)
%DDY_SHARM_S_8_8
%    OUT1 = DDY_SHARM_S_8_8(X,Y,Z)

%    This function was generated by the Symbolic Math Toolbox version 6.3.
%    09-Jan-2017 14:53:53

t2 = x.^2;
t3 = y.^2;
t4 = t2.^2;
t5 = t3.^2;
out1 = t2.*t4.*x.*5.013653233920352+t2.*t5.*x.*1.754778631872123e2-t3.*t4.*x.*1.052867179123274e2-t3.*t5.*x.*3.509557263744246e1;
