function out1 = ddy_sharm_C_5_1(x,y,z)
%DDY_SHARM_C_5_1
%    OUT1 = DDY_SHARM_C_5_1(X,Y,Z)

%    This function was generated by the Symbolic Math Toolbox version 6.3.
%    09-Jan-2017 14:53:20

t2 = y.^2;
t3 = x.^2;
out1 = x.*y.*z.^2.*-1.161895003862225e1+t2.*x.*y.*1.936491673103708+t3.*x.*y.*1.936491673103708;
