function out1 = ddy_sharm_C_8_3(x,y,z)
%DDY_SHARM_C_8_3
%    OUT1 = DDY_SHARM_C_8_3(X,Y,Z)

%    This function was generated by the Symbolic Math Toolbox version 6.3.
%    09-Jan-2017 14:53:47

t2 = z.^2;
t3 = t2.^2;
t4 = y.^2;
t5 = t4.^2;
t6 = x.^2;
t7 = t6.^2;
out1 = t3.*x.*y.*z.*-1.019558728077986e2-t5.*x.*y.*z.*5.73501784543867e1-t7.*x.*y.*z.*6.372242050487411+t2.*t4.*x.*y.*z.*2.548896820194964e2+t2.*t6.*x.*y.*z.*8.496322733983215e1-t4.*t6.*x.*y.*z.*6.372242050487411e1;
