function out1 = ddy_sharm_S_6_1(x,y,z)
%DDY_SHARM_S_6_1
%    OUT1 = DDY_SHARM_S_6_1(X,Y,Z)

%    This function was generated by the Symbolic Math Toolbox version 6.3.
%    09-Jan-2017 14:53:26

t2 = z.^2;
t3 = x.^2;
t4 = y.^2;
t5 = t2.^2;
out1 = t5.*z.*4.58257569495584+t3.^2.*z.*2.8641098093474+t4.^2.*z.*1.4320549046737e1-t2.*t3.*z.*1.14564392373896e1-t2.*t4.*z.*3.43693177121688e1+t3.*t4.*z.*1.71846588560844e1;
