function out1 = ddy_sharm_C_7_2(x,y,z)
%DDY_SHARM_C_7_2
%    OUT1 = DDY_SHARM_C_7_2(X,Y,Z)

%    This function was generated by the Symbolic Math Toolbox version 6.3.
%    09-Jan-2017 14:53:35

t2 = y.^2;
t3 = z.^2;
t4 = t3.^2;
t5 = t2.^2;
t6 = x.^2;
out1 = t6.^2.*y.*z.*6.075694404757369-t4.*y.*z.*1.944222209522358e1-t5.*y.*z.*1.822708321427211e1+t2.*t3.*y.*z.*6.48074069840786e1-t2.*t6.*y.*z.*1.215138880951474e1;
