function out1 = ddy_sharm_C_3_1(x,y,z)
%DDY_SHARM_C_3_1
%    OUT1 = DDY_SHARM_C_3_1(X,Y,Z)

%    This function was generated by the Symbolic Math Toolbox version 6.3.
%    09-Jan-2017 14:53:11

out1 = x.*y.*-1.224744871391589;
