function out1 = ddy_sharm_C_8_1(x,y,z)
%DDY_SHARM_C_8_1
%    OUT1 = DDY_SHARM_C_8_1(X,Y,Z)

%    This function was generated by the Symbolic Math Toolbox version 6.3.
%    09-Jan-2017 14:53:44

t2 = z.^2;
t3 = t2.^2;
t4 = y.^2;
t5 = t4.^2;
t6 = x.^2;
t7 = t6.^2;
out1 = t3.*x.*y.*z.*-6.3e1-t5.*x.*y.*z.*1.96875e1-t7.*x.*y.*z.*1.96875e1+t2.*t4.*x.*y.*z.*1.05e2+t2.*t6.*x.*y.*z.*1.05e2-t4.*t6.*x.*y.*z.*3.9375e1;
