function out1 = ddy_sharm_C_4_4(x,y,z)
%DDY_SHARM_C_4_4
%    OUT1 = DDY_SHARM_C_4_4(X,Y,Z)

%    This function was generated by the Symbolic Math Toolbox version 6.3.
%    09-Jan-2017 14:53:17

t2 = y.^2;
out1 = t2.*y.*2.958039891549808-x.^2.*y.*8.874119674649424;
