function out1 = ddy_sharm_S_8_2(x,y,z)
%DDY_SHARM_S_8_2
%    OUT1 = DDY_SHARM_S_8_2(X,Y,Z)

%    This function was generated by the Symbolic Math Toolbox version 6.3.
%    09-Jan-2017 14:53:46

t2 = x.^2;
t3 = y.^2;
t4 = t2.^2;
t5 = z.^2;
t6 = t3.^2;
t7 = t5.^2;
out1 = t2.*t4.*x.*-7.843687748756958e-1-t3.*t4.*x.*7.059318973881262-t2.*t6.*x.*1.176553162313544e1-t2.*t7.*x.*6.274950199005567e1-t3.*t6.*x.*5.490581424129871+t4.*t5.*x.*2.353106324627087e1-t3.*t7.*x.*1.88248505970167e2+t5.*t6.*x.*1.176553162313544e2+t5.*t7.*x.*2.509980079602227e1+t2.*t3.*t5.*x.*1.411863794776252e2;
