function out1 = ddy_sharm_S_6_5(x,y,z)
%DDY_SHARM_S_6_5
%    OUT1 = DDY_SHARM_S_6_5(X,Y,Z)

%    This function was generated by the Symbolic Math Toolbox version 6.3.
%    09-Jan-2017 14:53:31

t2 = x.^2;
t3 = y.^2;
out1 = t2.^2.*z.*1.163406904311643e1+t3.^2.*z.*1.163406904311643e1-t2.*t3.*z.*6.980441425869857e1;
