function out1 = ddy_sharm_S_9_7(x,y,z)
%DDY_SHARM_S_9_7
%    OUT1 = DDY_SHARM_S_9_7(X,Y,Z)

%    This function was generated by the Symbolic Math Toolbox version 6.3.
%    09-Jan-2017 14:54:04

t2 = y.^2;
t3 = t2.^2;
t4 = x.^2;
t5 = t4.^2;
t6 = z.^2;
out1 = t3.*t5.*3.102039675195076e1+t3.^2.*3.988336725250812-t5.^2.*3.102039675195076-t2.*t3.*t4.*6.204079350390153e1-t2.*t3.*t6.*4.963263480312122e1+t2.*t4.*t5.*3.722447610234092e1-t2.*t5.*t6.*7.444895220468183e2+t3.*t4.*t6.*7.444895220468183e2+t4.*t5.*t6.*4.963263480312122e1;
