function out1 = ddy_sharm_C_4_0(x,y,z)
%DDY_SHARM_C_4_0
%    OUT1 = DDY_SHARM_C_4_0(X,Y,Z)

%    This function was generated by the Symbolic Math Toolbox version 6.3.
%    09-Jan-2017 14:53:14

t2 = y.^2;
out1 = t2.*y.*1.5+x.^2.*y.*1.5-y.*z.^2.*6.0;
