function out1 = ddy_sharm_S_2_2(x,y,z)
%DDY_SHARM_S_2_2
%    OUT1 = DDY_SHARM_S_2_2(X,Y,Z)

%    This function was generated by the Symbolic Math Toolbox version 6.3.
%    09-Jan-2017 14:53:10

out1 = x.*1.732050807568877;
