function out1 = ddy_sharm_C_1_0(x,y,z)
%DDY_SHARM_C_1_0
%    OUT1 = DDY_SHARM_C_1_0(X,Y,Z)

%    This function was generated by the Symbolic Math Toolbox version 6.3.
%    09-Jan-2017 14:53:07

out1 = 0.0;
