function out1 = ddy_sharm_C_8_0(x,y,z)
%DDY_SHARM_C_8_0
%    OUT1 = DDY_SHARM_C_8_0(X,Y,Z)

%    This function was generated by the Symbolic Math Toolbox version 6.3.
%    09-Jan-2017 14:53:43

t2 = y.^2;
t3 = t2.^2;
t4 = x.^2;
t5 = z.^2;
t6 = t4.^2;
t7 = t5.^2;
out1 = t2.*t3.*y.*2.1875+t3.*t4.*y.*6.5625+t2.*t6.*y.*6.5625-t3.*t5.*y.*5.25e1+t2.*t7.*y.*1.05e2+t4.*t6.*y.*2.1875+t4.*t7.*y.*1.05e2-t5.*t6.*y.*5.25e1-t5.*t7.*y.*2.8e1-t2.*t4.*t5.*y.*1.05e2;
