function out1 = ddy_sharm_S_5_4(x,y,z)
%DDY_SHARM_S_5_4
%    OUT1 = DDY_SHARM_S_5_4(X,Y,Z)

%    This function was generated by the Symbolic Math Toolbox version 6.3.
%    09-Jan-2017 14:53:24

t2 = x.^2;
out1 = x.*y.^2.*z.*-2.662235902394827e1+t2.*x.*z.*8.874119674649425;
