function out1 = ddy_sharm_C_5_3(x,y,z)
%DDY_SHARM_C_5_3
%    OUT1 = DDY_SHARM_C_5_3(X,Y,Z)

%    This function was generated by the Symbolic Math Toolbox version 6.3.
%    09-Jan-2017 14:53:22

t2 = y.^2;
t3 = x.^2;
out1 = x.*y.*z.^2.*-2.509980079602227e1+t2.*x.*y.*6.274950199005567+t3.*x.*y.*2.091650066335189;
