function out1 = ddy_sharm_S_4_1(x,y,z)
%DDY_SHARM_S_4_1
%    OUT1 = DDY_SHARM_S_4_1(X,Y,Z)

%    This function was generated by the Symbolic Math Toolbox version 6.3.
%    09-Jan-2017 14:53:15

t2 = z.^2;
out1 = t2.*z.*3.162277660168379-x.^2.*z.*2.371708245126285-y.^2.*z.*7.115124735378854;
