function out1 = ddy_sharm_C_6_3(x,y,z)
%DDY_SHARM_C_6_3
%    OUT1 = DDY_SHARM_C_6_3(X,Y,Z)

%    This function was generated by the Symbolic Math Toolbox version 6.3.
%    09-Jan-2017 14:53:28

t2 = z.^2;
t3 = y.^2;
t4 = x.^2;
out1 = t2.*x.*y.*z.*-4.347413023856832e1+t3.*x.*y.*z.*3.260559767892624e1+t4.*x.*y.*z.*1.086853255964208e1;
