function out1 = ddy_sharm_S_3_3(x,y,z)
%DDY_SHARM_S_3_3
%    OUT1 = DDY_SHARM_S_3_3(X,Y,Z)

%    This function was generated by the Symbolic Math Toolbox version 6.3.
%    09-Jan-2017 14:53:13

out1 = x.^2.*2.371708245126285-y.^2.*2.371708245126285;
