function out1 = ddy_sharm_C_7_3(x,y,z)
%DDY_SHARM_C_7_3
%    OUT1 = DDY_SHARM_C_7_3(X,Y,Z)

%    This function was generated by the Symbolic Math Toolbox version 6.3.
%    09-Jan-2017 14:53:37

t2 = x.^2;
t3 = y.^2;
t4 = t3.^2;
t5 = t2.^2;
t6 = z.^2;
out1 = t6.^2.*x.*y.*-6.87386354243376e1-t4.*x.*y.*7.73309648523798-t5.*x.*y.*8.5923294280422e-1-t2.*t3.*x.*y.*8.5923294280422+t2.*t6.*x.*y.*3.43693177121688e1+t3.*t6.*x.*y.*1.031079531365064e2;
