function out1 = ddy_sharm_C_8_8(x,y,z)
%DDY_SHARM_C_8_8
%    OUT1 = DDY_SHARM_C_8_8(X,Y,Z)

%    This function was generated by the Symbolic Math Toolbox version 6.3.
%    09-Jan-2017 14:53:53

t2 = y.^2;
t3 = t2.^2;
t4 = x.^2;
t5 = t4.^2;
out1 = t2.*t3.*y.*5.013653233920352+t2.*t5.*y.*1.754778631872123e2-t3.*t4.*y.*1.052867179123274e2-t4.*t5.*y.*3.509557263744246e1;
