function out1 = ddy_sharm_S_4_2(x,y,z)
%DDY_SHARM_S_4_2
%    OUT1 = DDY_SHARM_S_4_2(X,Y,Z)

%    This function was generated by the Symbolic Math Toolbox version 6.3.
%    09-Jan-2017 14:53:16

t2 = x.^2;
out1 = t2.*x.*-1.118033988749895-x.*y.^2.*3.354101966249685+x.*z.^2.*6.708203932499369;
