function out1 = ddy_sharm_C_8_7(x,y,z)
%DDY_SHARM_C_8_7
%    OUT1 = DDY_SHARM_C_8_7(X,Y,Z)

%    This function was generated by the Symbolic Math Toolbox version 6.3.
%    09-Jan-2017 14:53:52

t2 = y.^2;
t3 = t2.^2;
t4 = x.^2;
t5 = t4.^2;
out1 = t3.*x.*y.*z.*-1.052867179123274e2-t5.*x.*y.*z.*1.052867179123274e2+t2.*t4.*x.*y.*z.*3.509557263744246e2;
