function out1 = ddy_sharm_C_8_2(x,y,z)
%DDY_SHARM_C_8_2
%    OUT1 = DDY_SHARM_C_8_2(X,Y,Z)

%    This function was generated by the Symbolic Math Toolbox version 6.3.
%    09-Jan-2017 14:53:45

t2 = y.^2;
t3 = t2.^2;
t4 = z.^2;
t5 = x.^2;
t6 = t5.^2;
t7 = t4.^2;
out1 = t2.*t3.*y.*3.137475099502783-t3.*t4.*y.*7.059318973881262e1+t3.*t5.*y.*4.706212649254175+t2.*t7.*y.*1.254990039801113e2+t4.*t6.*y.*2.353106324627087e1-t4.*t7.*y.*2.509980079602227e1-t5.*t6.*y.*1.568737549751392-t2.*t4.*t5.*y.*4.706212649254175e1;
