function out1 = ddy_sharm_S_8_5(x,y,z)
%DDY_SHARM_S_8_5
%    OUT1 = DDY_SHARM_S_8_5(X,Y,Z)

%    This function was generated by the Symbolic Math Toolbox version 6.3.
%    09-Jan-2017 14:53:50

t2 = x.^2;
t3 = z.^2;
t4 = y.^2;
t5 = t2.^2;
t6 = t4.^2;
out1 = t2.*t5.*z.*-1.48305862683341e1+t2.*t6.*z.*1.334752764150069e2+t3.*t5.*z.*5.932234507333641e1+t3.*t6.*z.*5.932234507333641e1+t4.*t5.*z.*4.449175880500231e1-t4.*t6.*z.*2.076282077566774e1-t2.*t3.*t4.*z.*3.559340704400184e2;
