function out1 = ddy_sharm_S_7_4(x,y,z)
%DDY_SHARM_S_7_4
%    OUT1 = DDY_SHARM_S_7_4(X,Y,Z)

%    This function was generated by the Symbolic Math Toolbox version 6.3.
%    09-Jan-2017 14:53:39

t2 = x.^2;
t3 = z.^2;
t4 = t2.^2;
t5 = y.^2;
out1 = t5.^2.*x.*z.*5.699506557588999e1-t4.*x.*z.*1.1399013115178e1+t2.*t3.*x.*z.*3.799671038392666e1-t3.*t5.*x.*z.*1.1399013115178e2;
