function out1 = ddy_sharm_S_3_1(x,y,z)
%DDY_SHARM_S_3_1
%    OUT1 = DDY_SHARM_S_3_1(X,Y,Z)

%    This function was generated by the Symbolic Math Toolbox version 6.3.
%    09-Jan-2017 14:53:11

out1 = x.^2.*-6.123724356957945e-1-y.^2.*1.837117307087384+z.^2.*2.449489742783178;
