function out1 = ddz_sharm_S_6_2(x,y,z)
%DDZ_SHARM_S_6_2
%    OUT1 = DDZ_SHARM_S_6_2(X,Y,Z)

%    This function was generated by the Symbolic Math Toolbox version 6.3.
%    09-Jan-2017 14:53:28

t2 = z.^2;
t3 = y.^2;
t4 = x.^2;
out1 = t2.*x.*y.*z.*5.796550698475775e1-t3.*x.*y.*z.*2.898275349237888e1-t4.*x.*y.*z.*2.898275349237888e1;
