function out1 = ddz_sharm_C_8_2(x,y,z)
%DDZ_SHARM_C_8_2
%    OUT1 = DDZ_SHARM_C_8_2(X,Y,Z)

%    This function was generated by the Symbolic Math Toolbox version 6.3.
%    09-Jan-2017 14:53:45

t2 = z.^2;
t3 = t2.^2;
t4 = x.^2;
t5 = y.^2;
t6 = t4.^2;
t7 = t5.^2;
out1 = t3.*t4.*z.*7.52994023880668e1-t2.*t6.*z.*1.254990039801113e2-t3.*t5.*z.*7.52994023880668e1+t2.*t7.*z.*1.254990039801113e2+t4.*t6.*z.*2.353106324627087e1-t4.*t7.*z.*2.353106324627087e1+t5.*t6.*z.*2.353106324627087e1-t5.*t7.*z.*2.353106324627087e1;
