function out1 = ddz_sharm_S_4_2(x,y,z)
%DDZ_SHARM_S_4_2
%    OUT1 = DDZ_SHARM_S_4_2(X,Y,Z)

%    This function was generated by the Symbolic Math Toolbox version 6.3.
%    09-Jan-2017 14:53:16

out1 = x.*y.*z.*1.341640786499874e1;
