function out1 = ddz_sharm_S_6_5(x,y,z)
%DDZ_SHARM_S_6_5
%    OUT1 = DDZ_SHARM_S_6_5(X,Y,Z)

%    This function was generated by the Symbolic Math Toolbox version 6.3.
%    09-Jan-2017 14:53:31

t2 = y.^2;
t3 = x.^2;
t4 = t2.^2;
out1 = t4.*y.*2.326813808623286+t3.^2.*y.*1.163406904311643e1-t2.*t3.*y.*2.326813808623286e1;
