function out1 = ddz_sharm_C_7_6(x,y,z)
%DDZ_SHARM_C_7_6
%    OUT1 = DDZ_SHARM_C_7_6(X,Y,Z)

%    This function was generated by the Symbolic Math Toolbox version 6.3.
%    09-Jan-2017 14:53:41

t2 = y.^2;
t3 = x.^2;
t4 = t3.^2;
t5 = t2.^2;
out1 = t2.*t4.*-3.632736894374543e1-t2.*t5.*2.421824596249695+t3.*t4.*2.421824596249695+t3.*t5.*3.632736894374543e1;
