function out1 = ddz_sharm_S_9_2(x,y,z)
%DDZ_SHARM_S_9_2
%    OUT1 = DDZ_SHARM_S_9_2(X,Y,Z)

%    This function was generated by the Symbolic Math Toolbox version 6.3.
%    09-Jan-2017 14:53:57

t2 = x.^2;
t3 = y.^2;
t4 = t3.^2;
t5 = t2.^2;
t6 = z.^2;
t7 = t6.^2;
out1 = t2.*t4.*x.*y.*-2.064842419834986e1-t2.*t5.*x.*y.*6.88280806611662-t3.*t4.*x.*y.*6.88280806611662-t3.*t5.*x.*y.*2.064842419834986e1-t2.*t7.*x.*y.*5.506246452893296e2-t3.*t7.*x.*y.*5.506246452893296e2+t4.*t6.*x.*y.*2.064842419834986e2+t5.*t6.*x.*y.*2.064842419834986e2+t6.*t7.*x.*y.*2.202498581157318e2+t2.*t3.*t6.*x.*y.*4.129684839669972e2;
