function out1 = ddz_sharm_S_7_1(x,y,z)
%DDZ_SHARM_S_7_1
%    OUT1 = DDZ_SHARM_S_7_1(X,Y,Z)

%    This function was generated by the Symbolic Math Toolbox version 6.3.
%    09-Jan-2017 14:53:34

t2 = y.^2;
t3 = z.^2;
t4 = t3.^2;
t5 = t2.^2;
t6 = x.^2;
out1 = t6.^2.*y.*z.*1.984313483298443e1+t4.*y.*z.*3.174901573277509e1+t5.*y.*z.*1.984313483298443e1-t2.*t3.*y.*z.*7.937253933193772e1+t2.*t6.*y.*z.*3.968626966596886e1-t3.*t6.*y.*z.*7.937253933193772e1;
