function out1 = ddz_sharm_S_5_1(x,y,z)
%DDZ_SHARM_S_5_1
%    OUT1 = DDZ_SHARM_S_5_1(X,Y,Z)

%    This function was generated by the Symbolic Math Toolbox version 6.3.
%    09-Jan-2017 14:53:20

t2 = z.^2;
t3 = y.^2;
out1 = x.^2.*y.*z.*-1.161895003862225e1+t2.*y.*z.*1.549193338482967e1-t3.*y.*z.*1.161895003862225e1;
