function out1 = ddz_sharm_S_4_1(x,y,z)
%DDZ_SHARM_S_4_1
%    OUT1 = DDZ_SHARM_S_4_1(X,Y,Z)

%    This function was generated by the Symbolic Math Toolbox version 6.3.
%    09-Jan-2017 14:53:15

t2 = y.^2;
out1 = t2.*y.*-2.371708245126285-x.^2.*y.*2.371708245126285+y.*z.^2.*9.486832980505138;
