function out1 = ddz_sharm_S_8_1(x,y,z)
%DDZ_SHARM_S_8_1
%    OUT1 = DDZ_SHARM_S_8_1(X,Y,Z)

%    This function was generated by the Symbolic Math Toolbox version 6.3.
%    09-Jan-2017 14:53:45

t2 = y.^2;
t3 = t2.^2;
t4 = x.^2;
t5 = z.^2;
t6 = t4.^2;
t7 = t5.^2;
out1 = t2.*t3.*y.*-3.28125-t3.*t4.*y.*9.84375-t2.*t6.*y.*9.84375+t3.*t5.*y.*7.875e1-t2.*t7.*y.*1.575e2-t4.*t6.*y.*3.28125-t4.*t7.*y.*1.575e2+t5.*t6.*y.*7.875e1+t5.*t7.*y.*4.2e1+t2.*t4.*t5.*y.*1.575e2;
