function out1 = ddz_sharm_C_3_1(x,y,z)
%DDZ_SHARM_C_3_1
%    OUT1 = DDZ_SHARM_C_3_1(X,Y,Z)

%    This function was generated by the Symbolic Math Toolbox version 6.3.
%    09-Jan-2017 14:53:11

out1 = x.*z.*4.898979485566356;
