function out1 = ddz_sharm_C_3_3(x,y,z)
%DDZ_SHARM_C_3_3
%    OUT1 = DDZ_SHARM_C_3_3(X,Y,Z)

%    This function was generated by the Symbolic Math Toolbox version 6.3.
%    09-Jan-2017 14:53:13

out1 = 0.0;
