function out1 = ddz_sharm_C_4_1(x,y,z)
%DDZ_SHARM_C_4_1
%    OUT1 = DDZ_SHARM_C_4_1(X,Y,Z)

%    This function was generated by the Symbolic Math Toolbox version 6.3.
%    09-Jan-2017 14:53:14

t2 = x.^2;
out1 = t2.*x.*-2.371708245126285-x.*y.^2.*2.371708245126285+x.*z.^2.*9.486832980505138;
