function out1 = ddz_sharm_C_5_0(x,y,z)
%DDZ_SHARM_C_5_0
%    OUT1 = DDZ_SHARM_C_5_0(X,Y,Z)

%    This function was generated by the Symbolic Math Toolbox version 6.3.
%    09-Jan-2017 14:53:19

t2 = x.^2;
t3 = y.^2;
t4 = z.^2;
out1 = t2.*t3.*3.75-t2.*t4.*1.5e1-t3.*t4.*1.5e1+t2.^2.*1.875+t3.^2.*1.875+t4.^2.*5.0;
