function out1 = ddz_sharm_C_7_4(x,y,z)
%DDZ_SHARM_C_7_4
%    OUT1 = DDZ_SHARM_C_7_4(X,Y,Z)

%    This function was generated by the Symbolic Math Toolbox version 6.3.
%    09-Jan-2017 14:53:39

t2 = y.^2;
t3 = x.^2;
t4 = t3.^2;
t5 = t2.^2;
t6 = z.^2;
out1 = t2.*t4.*1.42487663939725e1-t2.*t5.*2.8497532787945-t3.*t4.*2.8497532787945+t3.*t5.*1.42487663939725e1+t4.*t6.*2.8497532787945e1+t5.*t6.*2.8497532787945e1-t2.*t3.*t6.*1.7098519672767e2;
