function out1 = ddz_sharm_S_7_6(x,y,z)
%DDZ_SHARM_S_7_6
%    OUT1 = DDZ_SHARM_S_7_6(X,Y,Z)

%    This function was generated by the Symbolic Math Toolbox version 6.3.
%    09-Jan-2017 14:53:42

t2 = x.^2;
t3 = y.^2;
t4 = t3.^2;
t5 = t2.^2;
out1 = t4.*x.*y.*1.453094757749817e1+t5.*x.*y.*1.453094757749817e1-t2.*t3.*x.*y.*4.84364919249939e1;
