function out1 = ddz_sharm_C_7_0(x,y,z)
%DDZ_SHARM_C_7_0
%    OUT1 = DDZ_SHARM_C_7_0(X,Y,Z)

%    This function was generated by the Symbolic Math Toolbox version 6.3.
%    09-Jan-2017 14:53:33

t2 = y.^2;
t3 = x.^2;
t4 = z.^2;
t5 = t3.^2;
t6 = t4.^2;
t7 = t2.^2;
out1 = t2.*t5.*-6.5625-t2.*t6.*5.25e1-t3.*t5.*2.1875-t2.*t7.*2.1875-t3.*t6.*5.25e1+t4.*t5.*3.9375e1-t3.*t7.*6.5625+t4.*t6.*7.0+t4.*t7.*3.9375e1+t2.*t3.*t4.*7.875e1;
