function out1 = ddz_sharm_C_8_6(x,y,z)
%DDZ_SHARM_C_8_6
%    OUT1 = DDZ_SHARM_C_8_6(X,Y,Z)

%    This function was generated by the Symbolic Math Toolbox version 6.3.
%    09-Jan-2017 14:53:51

t2 = x.^2;
t3 = t2.^2;
t4 = y.^2;
t5 = t4.^2;
out1 = t2.*t3.*z.*1.281509120139221e1+t2.*t5.*z.*1.922263680208831e2-t3.*t4.*z.*1.922263680208831e2-t4.*t5.*z.*1.281509120139221e1;
