function out1 = ddz_sharm_S_6_4(x,y,z)
%DDZ_SHARM_S_6_4
%    OUT1 = DDZ_SHARM_S_6_4(X,Y,Z)

%    This function was generated by the Symbolic Math Toolbox version 6.3.
%    09-Jan-2017 14:53:30

t2 = y.^2;
t3 = x.^2;
out1 = t2.*x.*y.*z.*-3.968626966596886e1+t3.*x.*y.*z.*3.968626966596886e1;
