function out1 = ddz_sharm_C_6_2(x,y,z)
%DDZ_SHARM_C_6_2
%    OUT1 = DDZ_SHARM_C_6_2(X,Y,Z)

%    This function was generated by the Symbolic Math Toolbox version 6.3.
%    09-Jan-2017 14:53:27

t2 = z.^2;
t3 = x.^2;
t4 = y.^2;
out1 = t3.^2.*z.*-1.449137674618944e1+t4.^2.*z.*1.449137674618944e1+t2.*t3.*z.*2.898275349237888e1-t2.*t4.*z.*2.898275349237888e1;
