function out1 = ddz_sharm_C_8_7(x,y,z)
%DDZ_SHARM_C_8_7
%    OUT1 = DDZ_SHARM_C_8_7(X,Y,Z)

%    This function was generated by the Symbolic Math Toolbox version 6.3.
%    09-Jan-2017 14:53:52

t2 = x.^2;
t3 = y.^2;
t4 = t2.^2;
t5 = t3.^2;
out1 = t2.*t4.*x.*2.506826616960176+t2.*t5.*x.*8.773893159360615e1-t3.*t4.*x.*5.264335895616369e1-t3.*t5.*x.*1.754778631872123e1;
