function out1 = ddz_sharm_S_9_4(x,y,z)
%DDZ_SHARM_S_9_4
%    OUT1 = DDZ_SHARM_S_9_4(X,Y,Z)

%    This function was generated by the Symbolic Math Toolbox version 6.3.
%    09-Jan-2017 14:54:00

t2 = x.^2;
t3 = y.^2;
t4 = t3.^2;
t5 = t2.^2;
t6 = z.^2;
t7 = t6.^2;
out1 = t2.*t4.*x.*y.*-1.326487961686799e1+t2.*t5.*x.*y.*1.326487961686799e1-t3.*t4.*x.*y.*1.326487961686799e1+t3.*t5.*x.*y.*1.326487961686799e1+t2.*t7.*x.*y.*5.305951846747198e2-t3.*t7.*x.*y.*5.305951846747198e2+t4.*t6.*x.*y.*3.183571108048319e2-t5.*t6.*x.*y.*3.183571108048319e2;
