function out1 = ddz_sharm_S_6_1(x,y,z)
%DDZ_SHARM_S_6_1
%    OUT1 = DDZ_SHARM_S_6_1(X,Y,Z)

%    This function was generated by the Symbolic Math Toolbox version 6.3.
%    09-Jan-2017 14:53:26

t2 = y.^2;
t3 = x.^2;
t4 = z.^2;
t5 = t2.^2;
out1 = t5.*y.*2.8641098093474+t3.^2.*y.*2.8641098093474+t4.^2.*y.*2.29128784747792e1+t2.*t3.*y.*5.7282196186948-t2.*t4.*y.*3.43693177121688e1-t3.*t4.*y.*3.43693177121688e1;
