function out1 = ddz_sharm_C_9_5(x,y,z)
%DDZ_SHARM_C_9_5
%    OUT1 = DDZ_SHARM_C_9_5(X,Y,Z)

%    This function was generated by the Symbolic Math Toolbox version 6.3.
%    09-Jan-2017 14:54:00

t2 = x.^2;
t3 = t2.^2;
t4 = z.^2;
t5 = y.^2;
t6 = t5.^2;
out1 = t2.*t3.*x.*z.*-2.219638906444019e1+t3.*t4.*x.*z.*8.878555625776075e1+t2.*t6.*x.*z.*1.109819453222009e2+t3.*t5.*x.*z.*1.997675015799617e2+t4.*t6.*x.*z.*4.439277812888038e2-t5.*t6.*x.*z.*1.109819453222009e2-t2.*t4.*t5.*x.*z.*8.878555625776075e2;
