function out1 = ddz_sharm_C_4_3(x,y,z)
%DDZ_SHARM_C_4_3
%    OUT1 = DDZ_SHARM_C_4_3(X,Y,Z)

%    This function was generated by the Symbolic Math Toolbox version 6.3.
%    09-Jan-2017 14:53:16

t2 = x.^2;
out1 = t2.*x.*2.091650066335189-x.*y.^2.*6.274950199005567;
