function out1 = ddz_sharm_S_6_6(x,y,z)
%DDZ_SHARM_S_6_6
%    OUT1 = DDZ_SHARM_S_6_6(X,Y,Z)

%    This function was generated by the Symbolic Math Toolbox version 6.3.
%    09-Jan-2017 14:53:32

out1 = 0.0;
