function out1 = ddz_sharm_S_5_3(x,y,z)
%DDZ_SHARM_S_5_3
%    OUT1 = DDZ_SHARM_S_5_3(X,Y,Z)

%    This function was generated by the Symbolic Math Toolbox version 6.3.
%    09-Jan-2017 14:53:23

t2 = y.^2;
out1 = x.^2.*y.*z.*2.509980079602227e1-t2.*y.*z.*8.366600265340755;
