function out1 = ddz_sharm_C_7_1(x,y,z)
%DDZ_SHARM_C_7_1
%    OUT1 = DDZ_SHARM_C_7_1(X,Y,Z)

%    This function was generated by the Symbolic Math Toolbox version 6.3.
%    09-Jan-2017 14:53:34

t2 = x.^2;
t3 = z.^2;
t4 = t3.^2;
t5 = t2.^2;
t6 = y.^2;
out1 = t6.^2.*x.*z.*1.984313483298443e1+t4.*x.*z.*3.174901573277509e1+t5.*x.*z.*1.984313483298443e1-t2.*t3.*x.*z.*7.937253933193772e1+t2.*t6.*x.*z.*3.968626966596886e1-t3.*t6.*x.*z.*7.937253933193772e1;
