function out1 = ddz_sharm_C_9_3(x,y,z)
%DDZ_SHARM_C_9_3
%    OUT1 = DDZ_SHARM_C_9_3(X,Y,Z)

%    This function was generated by the Symbolic Math Toolbox version 6.3.
%    09-Jan-2017 14:53:58

t2 = x.^2;
t3 = z.^2;
t4 = t3.^2;
t5 = t2.^2;
t6 = y.^2;
t7 = t6.^2;
out1 = t2.*t4.*x.*z.*1.44187378088375e2+t2.*t5.*x.*z.*2.703513339157031e1-t3.*t5.*x.*z.*1.802342226104687e2-t2.*t7.*x.*z.*1.351756669578515e2+t3.*t7.*x.*z.*5.407026678314062e2-t4.*t6.*x.*z.*4.325621342651249e2-t5.*t6.*x.*z.*2.703513339157031e1-t6.*t7.*x.*z.*8.110540017471093e1+t2.*t3.*t6.*x.*z.*3.604684452209374e2;
