function out1 = ddz_sharm_S_9_1(x,y,z)
%DDZ_SHARM_S_9_1
%    OUT1 = DDZ_SHARM_S_9_1(X,Y,Z)

%    This function was generated by the Symbolic Math Toolbox version 6.3.
%    09-Jan-2017 14:53:56

t2 = y.^2;
t3 = z.^2;
t4 = t3.^2;
t5 = t2.^2;
t6 = x.^2;
t7 = t6.^2;
out1 = t2.*t4.*y.*z.*-2.817445651649735e2-t2.*t5.*y.*z.*2.934839220468474e1+t3.*t4.*y.*z.*5.366563145999495e1+t3.*t5.*y.*z.*2.347871376374779e2-t2.*t7.*y.*z.*8.804517661405422e1+t3.*t7.*y.*z.*2.347871376374779e2-t4.*t6.*y.*z.*2.817445651649735e2-t5.*t6.*y.*z.*8.804517661405422e1-t6.*t7.*y.*z.*2.934839220468474e1+t2.*t3.*t6.*y.*z.*4.695742752749558e2;
