function out1 = ddz_sharm_C_8_4(x,y,z)
%DDZ_SHARM_C_8_4
%    OUT1 = DDZ_SHARM_C_8_4(X,Y,Z)

%    This function was generated by the Symbolic Math Toolbox version 6.3.
%    09-Jan-2017 14:53:48

t2 = x.^2;
t3 = z.^2;
t4 = y.^2;
t5 = t2.^2;
t6 = t4.^2;
out1 = t2.*t5.*z.*-1.974366987163227e1+t2.*t6.*z.*9.871834935816137e1+t3.*t5.*z.*6.581223290544092e1+t3.*t6.*z.*6.581223290544092e1+t4.*t5.*z.*9.871834935816137e1-t4.*t6.*z.*1.974366987163227e1-t2.*t3.*t4.*z.*3.948733974326455e2;
