function out1 = ddz_sharm_S_7_5(x,y,z)
%DDZ_SHARM_S_7_5
%    OUT1 = DDZ_SHARM_S_7_5(X,Y,Z)

%    This function was generated by the Symbolic Math Toolbox version 6.3.
%    09-Jan-2017 14:53:40

t2 = y.^2;
t3 = t2.^2;
t4 = x.^2;
out1 = t4.^2.*y.*z.*5.699506557588999e1+t3.*y.*z.*1.1399013115178e1-t2.*t4.*y.*z.*1.1399013115178e2;
