function out1 = ddz_sharm_S_2_1(x,y,z)
%DDZ_SHARM_S_2_1
%    OUT1 = DDZ_SHARM_S_2_1(X,Y,Z)

%    This function was generated by the Symbolic Math Toolbox version 6.3.
%    09-Jan-2017 14:53:09

out1 = y.*1.732050807568877;
