function out1 = ddz_sharm_C_5_3(x,y,z)
%DDZ_SHARM_C_5_3
%    OUT1 = DDZ_SHARM_C_5_3(X,Y,Z)

%    This function was generated by the Symbolic Math Toolbox version 6.3.
%    09-Jan-2017 14:53:22

t2 = x.^2;
out1 = x.*y.^2.*z.*-2.509980079602227e1+t2.*x.*z.*8.366600265340755;
