function out1 = ddz_sharm_C_7_2(x,y,z)
%DDZ_SHARM_C_7_2
%    OUT1 = DDZ_SHARM_C_7_2(X,Y,Z)

%    This function was generated by the Symbolic Math Toolbox version 6.3.
%    09-Jan-2017 14:53:35

t2 = y.^2;
t3 = x.^2;
t4 = z.^2;
t5 = t3.^2;
t6 = t4.^2;
t7 = t2.^2;
out1 = t2.*t5.*3.037847202378684-t2.*t6.*4.860555523805895e1+t3.*t5.*3.037847202378684-t2.*t7.*3.037847202378684+t3.*t6.*4.860555523805895e1-t4.*t5.*4.860555523805895e1-t3.*t7.*3.037847202378684+t4.*t7.*4.860555523805895e1;
