function out1 = ddz_sharm_S_9_6(x,y,z)
%DDZ_SHARM_S_9_6
%    OUT1 = DDZ_SHARM_S_9_6(X,Y,Z)

%    This function was generated by the Symbolic Math Toolbox version 6.3.
%    09-Jan-2017 14:54:02

t2 = x.^2;
t3 = y.^2;
t4 = t3.^2;
t5 = t2.^2;
t6 = z.^2;
out1 = t2.*t4.*x.*y.*4.298312259625863e1-t2.*t5.*x.*y.*1.842133825553941e1-t3.*t4.*x.*y.*1.842133825553941e1+t3.*t5.*x.*y.*4.298312259625863e1+t4.*t6.*x.*y.*2.578987355775518e2+t5.*t6.*x.*y.*2.578987355775518e2-t2.*t3.*t6.*x.*y.*8.596624519251727e2;
