function out1 = ddz_sharm_C_9_8(x,y,z)
%DDZ_SHARM_C_9_8
%    OUT1 = DDZ_SHARM_C_9_8(X,Y,Z)

%    This function was generated by the Symbolic Math Toolbox version 6.3.
%    09-Jan-2017 14:54:04

t2 = y.^2;
t3 = t2.^2;
t4 = x.^2;
t5 = t4.^2;
out1 = t3.*t5.*1.808784412196403e2+t3.^2.*2.583977731709147+t5.^2.*2.583977731709147-t2.*t3.*t4.*7.235137648785613e1-t2.*t4.*t5.*7.235137648785613e1;
