function out1 = ddz_sharm_S_5_2(x,y,z)
%DDZ_SHARM_S_5_2
%    OUT1 = DDZ_SHARM_S_5_2(X,Y,Z)

%    This function was generated by the Symbolic Math Toolbox version 6.3.
%    09-Jan-2017 14:53:21

t2 = y.^2;
t3 = x.^2;
out1 = x.*y.*z.^2.*3.07408522978788e1-t2.*x.*y.*5.123475382979799-t3.*x.*y.*5.123475382979799;
