function out1 = ddz_sharm_S_8_2(x,y,z)
%DDZ_SHARM_S_8_2
%    OUT1 = DDZ_SHARM_S_8_2(X,Y,Z)

%    This function was generated by the Symbolic Math Toolbox version 6.3.
%    09-Jan-2017 14:53:46

t2 = z.^2;
t3 = t2.^2;
t4 = y.^2;
t5 = t4.^2;
t6 = x.^2;
t7 = t6.^2;
out1 = t3.*x.*y.*z.*1.505988047761336e2+t5.*x.*y.*z.*4.706212649254175e1+t7.*x.*y.*z.*4.706212649254175e1-t2.*t4.*x.*y.*z.*2.509980079602227e2-t2.*t6.*x.*y.*z.*2.509980079602227e2+t4.*t6.*x.*y.*z.*9.41242529850835e1;
