function out1 = ddz_sharm_C_4_4(x,y,z)
%DDZ_SHARM_C_4_4
%    OUT1 = DDZ_SHARM_C_4_4(X,Y,Z)

%    This function was generated by the Symbolic Math Toolbox version 6.3.
%    09-Jan-2017 14:53:18

out1 = 0.0;
