function out1 = ddz_sharm_C_6_3(x,y,z)
%DDZ_SHARM_C_6_3
%    OUT1 = DDZ_SHARM_C_6_3(X,Y,Z)

%    This function was generated by the Symbolic Math Toolbox version 6.3.
%    09-Jan-2017 14:53:28

t2 = x.^2;
t3 = y.^2;
t4 = t2.^2;
t5 = z.^2;
out1 = t4.*x.*-2.71713313991052+t3.^2.*x.*8.151399419731559+t2.*t3.*x.*5.434266279821039+t2.*t5.*x.*2.173706511928416e1-t3.*t5.*x.*6.521119535785247e1;
