function out1 = ddz_sharm_C_8_3(x,y,z)
%DDZ_SHARM_C_8_3
%    OUT1 = DDZ_SHARM_C_8_3(X,Y,Z)

%    This function was generated by the Symbolic Math Toolbox version 6.3.
%    09-Jan-2017 14:53:47

t2 = x.^2;
t3 = y.^2;
t4 = t2.^2;
t5 = z.^2;
t6 = t3.^2;
t7 = t5.^2;
out1 = t2.*t4.*x.*3.186121025243705-t3.*t4.*x.*3.186121025243705-t2.*t6.*x.*1.593060512621853e1+t2.*t7.*x.*8.496322733983215e1-t3.*t6.*x.*9.558363075731116-t4.*t5.*x.*6.372242050487411e1-t3.*t7.*x.*2.548896820194964e2+t5.*t6.*x.*1.911672615146223e2+t2.*t3.*t5.*x.*1.274448410097482e2;
