function out1 = ddz_sharm_C_9_6(x,y,z)
%DDZ_SHARM_C_9_6
%    OUT1 = DDZ_SHARM_C_9_6(X,Y,Z)

%    This function was generated by the Symbolic Math Toolbox version 6.3.
%    09-Jan-2017 14:54:02

t2 = y.^2;
t3 = t2.^2;
t4 = x.^2;
t5 = t4.^2;
t6 = z.^2;
out1 = t3.^2.*3.070223042589902-t5.^2.*3.070223042589902-t2.*t3.*t4.*4.298312259625863e1-t2.*t3.*t6.*4.298312259625863e1+t2.*t4.*t5.*4.298312259625863e1-t2.*t5.*t6.*6.447468389438795e2+t3.*t4.*t6.*6.447468389438795e2+t4.*t5.*t6.*4.298312259625863e1;
