function out1 = ddz_sharm_S_8_5(x,y,z)
%DDZ_SHARM_S_8_5
%    OUT1 = DDZ_SHARM_S_8_5(X,Y,Z)

%    This function was generated by the Symbolic Math Toolbox version 6.3.
%    09-Jan-2017 14:53:50

t2 = y.^2;
t3 = t2.^2;
t4 = x.^2;
t5 = t4.^2;
t6 = z.^2;
out1 = t2.*t3.*y.*-2.96611725366682+t2.*t5.*y.*1.48305862683341e1+t3.*t4.*y.*2.669505528300138e1+t3.*t6.*y.*3.559340704400184e1-t4.*t5.*y.*1.48305862683341e1+t5.*t6.*y.*1.779670352200092e2-t2.*t4.*t6.*y.*3.559340704400184e2;
