function out1 = ddz_sharm_C_6_4(x,y,z)
%DDZ_SHARM_C_6_4
%    OUT1 = DDZ_SHARM_C_6_4(X,Y,Z)

%    This function was generated by the Symbolic Math Toolbox version 6.3.
%    09-Jan-2017 14:53:29

t2 = x.^2;
t3 = y.^2;
out1 = t2.^2.*z.*9.921567416492214+t3.^2.*z.*9.921567416492214-t2.*t3.*z.*5.952940449895329e1;
