function out1 = ddz_sharm_C_4_2(x,y,z)
%DDZ_SHARM_C_4_2
%    OUT1 = DDZ_SHARM_C_4_2(X,Y,Z)

%    This function was generated by the Symbolic Math Toolbox version 6.3.
%    09-Jan-2017 14:53:15

out1 = x.^2.*z.*6.708203932499369-y.^2.*z.*6.708203932499369;
