function out1 = ddz_sharm_C_8_1(x,y,z)
%DDZ_SHARM_C_8_1
%    OUT1 = DDZ_SHARM_C_8_1(X,Y,Z)

%    This function was generated by the Symbolic Math Toolbox version 6.3.
%    09-Jan-2017 14:53:44

t2 = x.^2;
t3 = y.^2;
t4 = t2.^2;
t5 = z.^2;
t6 = t3.^2;
t7 = t5.^2;
out1 = t2.*t4.*x.*-3.28125-t3.*t4.*x.*9.84375-t2.*t6.*x.*9.84375-t2.*t7.*x.*1.575e2-t3.*t6.*x.*3.28125+t4.*t5.*x.*7.875e1-t3.*t7.*x.*1.575e2+t5.*t6.*x.*7.875e1+t5.*t7.*x.*4.2e1+t2.*t3.*t5.*x.*1.575e2;
