function out1 = ddz_sharm_S_7_4(x,y,z)
%DDZ_SHARM_S_7_4
%    OUT1 = DDZ_SHARM_S_7_4(X,Y,Z)

%    This function was generated by the Symbolic Math Toolbox version 6.3.
%    09-Jan-2017 14:53:39

t2 = y.^2;
t3 = t2.^2;
t4 = x.^2;
t5 = t4.^2;
t6 = z.^2;
out1 = t3.*x.*y.*1.1399013115178e1-t5.*x.*y.*1.1399013115178e1-t2.*t6.*x.*y.*1.1399013115178e2+t4.*t6.*x.*y.*1.1399013115178e2;
