function out1 = ddz_sharm_S_4_3(x,y,z)
%DDZ_SHARM_S_4_3
%    OUT1 = DDZ_SHARM_S_4_3(X,Y,Z)

%    This function was generated by the Symbolic Math Toolbox version 6.3.
%    09-Jan-2017 14:53:17

t2 = y.^2;
out1 = t2.*y.*-2.091650066335189+x.^2.*y.*6.274950199005567;
