function out1 = ddz_sharm_C_3_0(x,y,z)
%DDZ_SHARM_C_3_0
%    OUT1 = DDZ_SHARM_C_3_0(X,Y,Z)

%    This function was generated by the Symbolic Math Toolbox version 6.3.
%    09-Jan-2017 14:53:10

out1 = x.^2.*-1.5-y.^2.*1.5+z.^2.*3.0;
