function out1 = sharm_S_6_6(x,y,z)
%SHARM_S_6_6
%    OUT1 = SHARM_S_6_6(X,Y,Z)

%    This function was generated by the Symbolic Math Toolbox version 6.3.
%    09-Jan-2017 14:53:32

t2 = x.^2;
t3 = y.^2;
t4 = t3.^2;
t5 = t2.^2;
out1 = t4.*x.*y.*4.030159736288377+t5.*x.*y.*4.030159736288377-t2.*t3.*x.*y.*1.343386578762792e1;
