function out1 = sharm_C_6_4(x,y,z)
%SHARM_C_6_4
%    OUT1 = SHARM_C_6_4(X,Y,Z)

%    This function was generated by the Symbolic Math Toolbox version 6.3.
%    09-Jan-2017 14:53:29

t2 = y.^2;
t3 = x.^2;
t4 = t3.^2;
t5 = t2.^2;
t6 = z.^2;
out1 = t2.*t4.*2.480391854123054-t2.*t5.*4.960783708246107e-1-t3.*t4.*4.960783708246107e-1+t3.*t5.*2.480391854123054+t4.*t6.*4.960783708246107+t5.*t6.*4.960783708246107-t2.*t3.*t6.*2.976470224947664e1;
