function out1 = sharm_S_7_5(x,y,z)
%SHARM_S_7_5
%    OUT1 = SHARM_S_7_5(X,Y,Z)

%    This function was generated by the Symbolic Math Toolbox version 6.3.
%    09-Jan-2017 14:53:40

t2 = y.^2;
t3 = t2.^2;
t4 = x.^2;
t5 = t4.^2;
t6 = z.^2;
out1 = t2.*t3.*y.*-4.749588797990833e-1+t2.*t5.*y.*2.374794398995416+t3.*t4.*y.*4.274629918191749+t3.*t6.*y.*5.699506557588999-t4.*t5.*y.*2.374794398995416+t5.*t6.*y.*2.8497532787945e1-t2.*t4.*t6.*y.*5.699506557588999e1;
