function out1 = sharm_C_8_7(x,y,z)
%SHARM_C_8_7
%    OUT1 = SHARM_C_8_7(X,Y,Z)

%    This function was generated by the Symbolic Math Toolbox version 6.3.
%    09-Jan-2017 14:53:52

t2 = x.^2;
t3 = t2.^2;
t4 = y.^2;
t5 = t4.^2;
out1 = t2.*t3.*x.*z.*2.506826616960176+t2.*t5.*x.*z.*8.773893159360615e1-t3.*t4.*x.*z.*5.264335895616369e1-t4.*t5.*x.*z.*1.754778631872123e1;
