function out1 = sharm_C_3_2(x,y,z)
%SHARM_C_3_2
%    OUT1 = SHARM_C_3_2(X,Y,Z)

%    This function was generated by the Symbolic Math Toolbox version 6.3.
%    09-Jan-2017 14:53:12

out1 = x.^2.*z.*1.936491673103708-y.^2.*z.*1.936491673103708;
