function out1 = sharm_C_8_3(x,y,z)
%SHARM_C_8_3
%    OUT1 = SHARM_C_8_3(X,Y,Z)

%    This function was generated by the Symbolic Math Toolbox version 6.3.
%    09-Jan-2017 14:53:46

t2 = x.^2;
t3 = z.^2;
t4 = t3.^2;
t5 = t2.^2;
t6 = y.^2;
t7 = t6.^2;
out1 = t2.*t4.*x.*z.*1.699264546796643e1+t2.*t5.*x.*z.*3.186121025243705-t3.*t5.*x.*z.*2.124080683495804e1-t2.*t7.*x.*z.*1.593060512621853e1+t3.*t7.*x.*z.*6.372242050487411e1-t4.*t6.*x.*z.*5.097793640389929e1-t5.*t6.*x.*z.*3.186121025243705-t6.*t7.*x.*z.*9.558363075731116+t2.*t3.*t6.*x.*z.*4.248161366991607e1;
