function out1 = sharm_S_9_6(x,y,z)
%SHARM_S_9_6
%    OUT1 = SHARM_S_9_6(X,Y,Z)

%    This function was generated by the Symbolic Math Toolbox version 6.3.
%    09-Jan-2017 14:54:02

t2 = y.^2;
t3 = t2.^2;
t4 = x.^2;
t5 = t4.^2;
t6 = z.^2;
out1 = t2.*t3.*x.*y.*z.*-1.842133825553941e1+t2.*t5.*x.*y.*z.*4.298312259625863e1+t3.*t4.*x.*y.*z.*4.298312259625863e1+t3.*t6.*x.*y.*z.*8.596624519251727e1-t4.*t5.*x.*y.*z.*1.842133825553941e1+t5.*t6.*x.*y.*z.*8.596624519251727e1-t2.*t4.*t6.*x.*y.*z.*2.865541506417242e2;
