function out1 = sharm_S_7_3(x,y,z)
%SHARM_S_7_3
%    OUT1 = SHARM_S_7_3(X,Y,Z)

%    This function was generated by the Symbolic Math Toolbox version 6.3.
%    09-Jan-2017 14:53:37

t2 = y.^2;
t3 = t2.^2;
t4 = x.^2;
t5 = z.^2;
t6 = t4.^2;
t7 = t5.^2;
out1 = t2.*t3.*y.*-4.2961647140211e-1+t3.*t4.*y.*4.2961647140211e-1+t2.*t6.*y.*2.14808235701055+t3.*t5.*y.*8.5923294280422-t2.*t7.*y.*1.14564392373896e1+t4.*t6.*y.*1.28884941420633+t4.*t7.*y.*3.43693177121688e1-t5.*t6.*y.*2.57769882841266e1-t2.*t4.*t5.*y.*1.71846588560844e1;
