function out1 = sharm_C_6_6(x,y,z)
%SHARM_C_6_6
%    OUT1 = SHARM_C_6_6(X,Y,Z)

%    This function was generated by the Symbolic Math Toolbox version 6.3.
%    09-Jan-2017 14:53:31

t2 = y.^2;
t3 = x.^2;
t4 = t3.^2;
t5 = t2.^2;
out1 = t2.*t4.*-1.007539934072094e1-t2.*t5.*6.716932893813961e-1+t3.*t4.*6.716932893813961e-1+t3.*t5.*1.007539934072094e1;
