function out1 = sharm_S_9_4(x,y,z)
%SHARM_S_9_4
%    OUT1 = SHARM_S_9_4(X,Y,Z)

%    This function was generated by the Symbolic Math Toolbox version 6.3.
%    09-Jan-2017 14:53:59

t2 = y.^2;
t3 = t2.^2;
t4 = x.^2;
t5 = t4.^2;
t6 = z.^2;
t7 = t6.^2;
out1 = t2.*t3.*x.*y.*z.*-1.326487961686799e1+t2.*t5.*x.*y.*z.*1.326487961686799e1-t3.*t4.*x.*y.*z.*1.326487961686799e1-t2.*t7.*x.*y.*z.*1.06119036934944e2+t3.*t6.*x.*y.*z.*1.06119036934944e2+t4.*t5.*x.*y.*z.*1.326487961686799e1+t4.*t7.*x.*y.*z.*1.06119036934944e2-t5.*t6.*x.*y.*z.*1.06119036934944e2;
