function out1 = sharm_C_4_3(x,y,z)
%SHARM_C_4_3
%    OUT1 = SHARM_C_4_3(X,Y,Z)

%    This function was generated by the Symbolic Math Toolbox version 6.3.
%    09-Jan-2017 14:53:16

t2 = x.^2;
out1 = x.*y.^2.*z.*-6.274950199005567+t2.*x.*z.*2.091650066335189;
