function out1 = sharm_S_8_8(x,y,z)
%SHARM_S_8_8
%    OUT1 = SHARM_S_8_8(X,Y,Z)

%    This function was generated by the Symbolic Math Toolbox version 6.3.
%    09-Jan-2017 14:53:53

t2 = x.^2;
t3 = y.^2;
t4 = t3.^2;
t5 = t2.^2;
out1 = t2.*t4.*x.*y.*3.509557263744246e1+t2.*t5.*x.*y.*5.013653233920352-t3.*t4.*x.*y.*5.013653233920352-t3.*t5.*x.*y.*3.509557263744246e1;
