function out1 = sharm_C_6_5(x,y,z)
%SHARM_C_6_5
%    OUT1 = SHARM_C_6_5(X,Y,Z)

%    This function was generated by the Symbolic Math Toolbox version 6.3.
%    09-Jan-2017 14:53:30

t2 = x.^2;
t3 = t2.^2;
t4 = y.^2;
out1 = t4.^2.*x.*z.*1.163406904311643e1+t3.*x.*z.*2.326813808623286-t2.*t4.*x.*z.*2.326813808623286e1;
