function out1 = sharm_S_6_2(x,y,z)
%SHARM_S_6_2
%    OUT1 = SHARM_S_6_2(X,Y,Z)

%    This function was generated by the Symbolic Math Toolbox version 6.3.
%    09-Jan-2017 14:53:27

t2 = x.^2;
t3 = y.^2;
t4 = t3.^2;
t5 = t2.^2;
t6 = z.^2;
out1 = t6.^2.*x.*y.*1.449137674618944e1+t4.*x.*y.*9.057110466368399e-1+t5.*x.*y.*9.057110466368399e-1+t2.*t3.*x.*y.*1.81142209327368-t2.*t6.*x.*y.*1.449137674618944e1-t3.*t6.*x.*y.*1.449137674618944e1;
