function out1 = sharm_C_7_0(x,y,z)
%SHARM_C_7_0
%    OUT1 = SHARM_C_7_0(X,Y,Z)

%    This function was generated by the Symbolic Math Toolbox version 6.3.
%    09-Jan-2017 14:53:32

t2 = z.^2;
t3 = t2.^2;
t4 = x.^2;
t5 = y.^2;
t6 = t4.^2;
t7 = t5.^2;
out1 = t2.*t3.*z-t3.*t4.*z.*1.05e1+t2.*t6.*z.*1.3125e1-t3.*t5.*z.*1.05e1+t2.*t7.*z.*1.3125e1-t4.*t6.*z.*2.1875-t4.*t7.*z.*6.5625-t5.*t6.*z.*6.5625-t5.*t7.*z.*2.1875+t2.*t4.*t5.*z.*2.625e1;
