function out1 = sharm_C_2_1(x,y,z)
%SHARM_C_2_1
%    OUT1 = SHARM_C_2_1(X,Y,Z)

%    This function was generated by the Symbolic Math Toolbox version 6.3.
%    09-Jan-2017 14:53:08

out1 = x.*z.*1.732050807568877;
