function out1 = sharm_S_4_1(x,y,z)
%SHARM_S_4_1
%    OUT1 = SHARM_S_4_1(X,Y,Z)

%    This function was generated by the Symbolic Math Toolbox version 6.3.
%    09-Jan-2017 14:53:14

t2 = z.^2;
t3 = y.^2;
out1 = x.^2.*y.*z.*-2.371708245126285+t2.*y.*z.*3.162277660168379-t3.*y.*z.*2.371708245126285;
