function out1 = sharm_C_8_5(x,y,z)
%SHARM_C_8_5
%    OUT1 = SHARM_C_8_5(X,Y,Z)

%    This function was generated by the Symbolic Math Toolbox version 6.3.
%    09-Jan-2017 14:53:49

t2 = x.^2;
t3 = t2.^2;
t4 = z.^2;
t5 = y.^2;
t6 = t5.^2;
out1 = t2.*t3.*x.*z.*-2.96611725366682+t3.*t4.*x.*z.*1.186446901466728e1+t2.*t6.*x.*z.*1.48305862683341e1+t3.*t5.*x.*z.*2.669505528300138e1+t4.*t6.*x.*z.*5.932234507333641e1-t5.*t6.*x.*z.*1.48305862683341e1-t2.*t4.*t5.*x.*z.*1.186446901466728e2;
