function out1 = sharm_S_9_8(x,y,z)
%SHARM_S_9_8
%    OUT1 = SHARM_S_9_8(X,Y,Z)

%    This function was generated by the Symbolic Math Toolbox version 6.3.
%    09-Jan-2017 14:54:04

t2 = y.^2;
t3 = t2.^2;
t4 = x.^2;
t5 = t4.^2;
out1 = t2.*t3.*x.*y.*z.*-2.067182185367318e1-t2.*t5.*x.*y.*z.*1.447027529757123e2+t3.*t4.*x.*y.*z.*1.447027529757123e2+t4.*t5.*x.*y.*z.*2.067182185367318e1;
