function out1 = sharm_S_7_2(x,y,z)
%SHARM_S_7_2
%    OUT1 = SHARM_S_7_2(X,Y,Z)

%    This function was generated by the Symbolic Math Toolbox version 6.3.
%    09-Jan-2017 14:53:36

t2 = z.^2;
t3 = t2.^2;
t4 = y.^2;
t5 = t4.^2;
t6 = x.^2;
t7 = t6.^2;
out1 = t3.*x.*y.*z.*1.944222209522358e1+t5.*x.*y.*z.*6.075694404757369+t7.*x.*y.*z.*6.075694404757369-t2.*t4.*x.*y.*z.*3.24037034920393e1-t2.*t6.*x.*y.*z.*3.24037034920393e1+t4.*t6.*x.*y.*z.*1.215138880951474e1;
