function out1 = sharm_S_4_2(x,y,z)
%SHARM_S_4_2
%    OUT1 = SHARM_S_4_2(X,Y,Z)

%    This function was generated by the Symbolic Math Toolbox version 6.3.
%    09-Jan-2017 14:53:15

t2 = y.^2;
t3 = x.^2;
out1 = x.*y.*z.^2.*6.708203932499369-t2.*x.*y.*1.118033988749895-t3.*x.*y.*1.118033988749895;
