function out1 = sharm_C_7_4(x,y,z)
%SHARM_C_7_4
%    OUT1 = SHARM_C_7_4(X,Y,Z)

%    This function was generated by the Symbolic Math Toolbox version 6.3.
%    09-Jan-2017 14:53:38

t2 = x.^2;
t3 = z.^2;
t4 = y.^2;
t5 = t2.^2;
t6 = t4.^2;
out1 = t2.*t5.*z.*-2.8497532787945+t2.*t6.*z.*1.42487663939725e1+t3.*t5.*z.*9.499177595981665+t3.*t6.*z.*9.499177595981665+t4.*t5.*z.*1.42487663939725e1-t4.*t6.*z.*2.8497532787945-t2.*t3.*t4.*z.*5.699506557588999e1;
