function out1 = sharm_C_4_1(x,y,z)
%SHARM_C_4_1
%    OUT1 = SHARM_C_4_1(X,Y,Z)

%    This function was generated by the Symbolic Math Toolbox version 6.3.
%    09-Jan-2017 14:53:14

t2 = z.^2;
t3 = x.^2;
out1 = x.*y.^2.*z.*-2.371708245126285+t2.*x.*z.*3.162277660168379-t3.*x.*z.*2.371708245126285;
