function out1 = sharm_C_2_2(x,y,z)
%SHARM_C_2_2
%    OUT1 = SHARM_C_2_2(X,Y,Z)

%    This function was generated by the Symbolic Math Toolbox version 6.3.
%    09-Jan-2017 14:53:09

out1 = x.^2.*8.660254037844386e-1-y.^2.*8.660254037844386e-1;
