function out1 = sharm_S_6_4(x,y,z)
%SHARM_S_6_4
%    OUT1 = SHARM_S_6_4(X,Y,Z)

%    This function was generated by the Symbolic Math Toolbox version 6.3.
%    09-Jan-2017 14:53:29

t2 = y.^2;
t3 = t2.^2;
t4 = x.^2;
t5 = t4.^2;
t6 = z.^2;
out1 = t3.*x.*y.*1.984313483298443-t5.*x.*y.*1.984313483298443-t2.*t6.*x.*y.*1.984313483298443e1+t4.*t6.*x.*y.*1.984313483298443e1;
