function out1 = sharm_C_6_0(x,y,z)
%SHARM_C_6_0
%    OUT1 = SHARM_C_6_0(X,Y,Z)

%    This function was generated by the Symbolic Math Toolbox version 6.3.
%    09-Jan-2017 14:53:25

t2 = y.^2;
t3 = x.^2;
t4 = z.^2;
t5 = t3.^2;
t6 = t4.^2;
t7 = t2.^2;
out1 = t2.*t5.*-9.375e-1-t2.*t6.*7.5-t3.*t5.*3.125e-1-t2.*t7.*3.125e-1-t3.*t6.*7.5+t4.*t5.*5.625-t3.*t7.*9.375e-1+t4.*t6+t4.*t7.*5.625+t2.*t3.*t4.*1.125e1;
