function out1 = sharm_S_8_6(x,y,z)
%SHARM_S_8_6
%    OUT1 = SHARM_S_8_6(X,Y,Z)

%    This function was generated by the Symbolic Math Toolbox version 6.3.
%    09-Jan-2017 14:53:51

t2 = x.^2;
t3 = y.^2;
t4 = t3.^2;
t5 = t2.^2;
t6 = z.^2;
out1 = t2.*t4.*x.*y.*6.407545600696104-t2.*t5.*x.*y.*2.746090971726902-t3.*t4.*x.*y.*2.746090971726902+t3.*t5.*x.*y.*6.407545600696104+t4.*t6.*x.*y.*3.844527360417662e1+t5.*t6.*x.*y.*3.844527360417662e1-t2.*t3.*t6.*x.*y.*1.281509120139221e2;
