function out1 = sharm_C_9_0(x,y,z)
%SHARM_C_9_0
%    OUT1 = SHARM_C_9_0(X,Y,Z)

%    This function was generated by the Symbolic Math Toolbox version 6.3.
%    09-Jan-2017 14:53:54

t2 = z.^2;
t3 = t2.^2;
t4 = x.^2;
t5 = t4.^2;
t6 = y.^2;
t7 = t6.^2;
t8 = t3.^2;
out1 = t8.*z+t5.^2.*z.*2.4609375+t7.^2.*z.*2.4609375+t3.*t5.*z.*4.725e1+t3.*t7.*z.*4.725e1+t5.*t7.*z.*1.4765625e1-t2.*t3.*t4.*z.*1.8e1-t2.*t3.*t6.*z.*1.8e1-t2.*t4.*t5.*z.*2.625e1-t2.*t4.*t7.*z.*7.875e1-t2.*t5.*t6.*z.*7.875e1+t3.*t4.*t6.*z.*9.45e1-t2.*t6.*t7.*z.*2.625e1+t4.*t5.*t6.*z.*9.84375+t4.*t6.*t7.*z.*9.84375;
