function out1 = sharm_S_2_1(x,y,z)
%SHARM_S_2_1
%    OUT1 = SHARM_S_2_1(X,Y,Z)

%    This function was generated by the Symbolic Math Toolbox version 6.3.
%    09-Jan-2017 14:53:09

out1 = y.*z.*1.732050807568877;
