function out1 = sharm_C_7_2(x,y,z)
%SHARM_C_7_2
%    OUT1 = SHARM_C_7_2(X,Y,Z)

%    This function was generated by the Symbolic Math Toolbox version 6.3.
%    09-Jan-2017 14:53:35

t2 = z.^2;
t3 = t2.^2;
t4 = x.^2;
t5 = y.^2;
t6 = t4.^2;
t7 = t5.^2;
out1 = t3.*t4.*z.*9.72111104761179-t2.*t6.*z.*1.620185174601965e1-t3.*t5.*z.*9.72111104761179+t2.*t7.*z.*1.620185174601965e1+t4.*t6.*z.*3.037847202378684-t4.*t7.*z.*3.037847202378684+t5.*t6.*z.*3.037847202378684-t5.*t7.*z.*3.037847202378684;
