function out1 = sharm_C_8_8(x,y,z)
%SHARM_C_8_8
%    OUT1 = SHARM_C_8_8(X,Y,Z)

%    This function was generated by the Symbolic Math Toolbox version 6.3.
%    09-Jan-2017 14:53:53

t2 = y.^2;
t3 = t2.^2;
t4 = x.^2;
t5 = t4.^2;
out1 = t3.*t5.*4.386946579680308e1+t3.^2.*6.267066542400439e-1+t5.^2.*6.267066542400439e-1-t2.*t3.*t4.*1.754778631872123e1-t2.*t4.*t5.*1.754778631872123e1;
