function out1 = sharm_S_3_2(x,y,z)
%SHARM_S_3_2
%    OUT1 = SHARM_S_3_2(X,Y,Z)

%    This function was generated by the Symbolic Math Toolbox version 6.3.
%    09-Jan-2017 14:53:12

out1 = x.*y.*z.*3.872983346207417;
