function out1 = sharm_S_7_6(x,y,z)
%SHARM_S_7_6
%    OUT1 = SHARM_S_7_6(X,Y,Z)

%    This function was generated by the Symbolic Math Toolbox version 6.3.
%    09-Jan-2017 14:53:41

t2 = y.^2;
t3 = t2.^2;
t4 = x.^2;
t5 = t4.^2;
out1 = t3.*x.*y.*z.*1.453094757749817e1+t5.*x.*y.*z.*1.453094757749817e1-t2.*t4.*x.*y.*z.*4.84364919249939e1;
