function out1 = sharm_S_9_9(x,y,z)
%SHARM_S_9_9
%    OUT1 = SHARM_S_9_9(X,Y,Z)

%    This function was generated by the Symbolic Math Toolbox version 6.3.
%    09-Jan-2017 14:54:06

t2 = y.^2;
t3 = t2.^2;
t4 = x.^2;
t5 = t4.^2;
t6 = t3.^2;
out1 = t6.*y.*6.090493921755237e-1+t5.^2.*y.*5.481444529579714+t3.*t5.*y.*7.674022341411599e1-t2.*t3.*t4.*y.*2.192577811831885e1-t2.*t4.*t5.*y.*5.116014894274399e1;
