function out1 = sharm_C_4_2(x,y,z)
%SHARM_C_4_2
%    OUT1 = SHARM_C_4_2(X,Y,Z)

%    This function was generated by the Symbolic Math Toolbox version 6.3.
%    09-Jan-2017 14:53:15

t2 = z.^2;
t3 = x.^2;
t4 = y.^2;
out1 = t2.*t3.*3.354101966249685-t2.*t4.*3.354101966249685-t3.^2.*5.590169943749474e-1+t4.^2.*5.590169943749474e-1;
