function out1 = sharm_S_6_3(x,y,z)
%SHARM_S_6_3
%    OUT1 = SHARM_S_6_3(X,Y,Z)

%    This function was generated by the Symbolic Math Toolbox version 6.3.
%    09-Jan-2017 14:53:28

t2 = y.^2;
t3 = z.^2;
t4 = t2.^2;
t5 = x.^2;
out1 = t5.^2.*y.*z.*-8.151399419731559+t4.*y.*z.*2.71713313991052-t2.*t3.*y.*z.*7.245688373094719-t2.*t5.*y.*z.*5.434266279821039+t3.*t5.*y.*z.*2.173706511928416e1;
