function out1 = sharm_C_3_1(x,y,z)
%SHARM_C_3_1
%    OUT1 = SHARM_C_3_1(X,Y,Z)

%    This function was generated by the Symbolic Math Toolbox version 6.3.
%    09-Jan-2017 14:53:11

t2 = x.^2;
out1 = t2.*x.*-6.123724356957945e-1-x.*y.^2.*6.123724356957945e-1+x.*z.^2.*2.449489742783178;
