function out1 = sharm_C_4_0(x,y,z)
%SHARM_C_4_0
%    OUT1 = SHARM_C_4_0(X,Y,Z)

%    This function was generated by the Symbolic Math Toolbox version 6.3.
%    09-Jan-2017 14:53:13

t2 = x.^2;
t3 = y.^2;
t4 = z.^2;
out1 = t2.*t3.*7.5e-1-t2.*t4.*3.0-t3.*t4.*3.0+t2.^2.*3.75e-1+t3.^2.*3.75e-1+t4.^2;
