function out1 = sharm_S_3_3(x,y,z)
%SHARM_S_3_3
%    OUT1 = SHARM_S_3_3(X,Y,Z)

%    This function was generated by the Symbolic Math Toolbox version 6.3.
%    09-Jan-2017 14:53:13

t2 = y.^2;
out1 = t2.*y.*-7.905694150420948e-1+x.^2.*y.*2.371708245126285;
