function out1 = sharm_C_5_0(x,y,z)
%SHARM_C_5_0
%    OUT1 = SHARM_C_5_0(X,Y,Z)

%    This function was generated by the Symbolic Math Toolbox version 6.3.
%    09-Jan-2017 14:53:19

t2 = z.^2;
t3 = x.^2;
t4 = y.^2;
t5 = t2.^2;
out1 = t5.*z+t3.^2.*z.*1.875+t4.^2.*z.*1.875-t2.*t3.*z.*5.0-t2.*t4.*z.*5.0+t3.*t4.*z.*3.75;
