function out1 = sharm_C_9_6(x,y,z)
%SHARM_C_9_6
%    OUT1 = SHARM_C_9_6(X,Y,Z)

%    This function was generated by the Symbolic Math Toolbox version 6.3.
%    09-Jan-2017 14:54:01

t2 = x.^2;
t3 = t2.^2;
t4 = z.^2;
t5 = y.^2;
t6 = t5.^2;
out1 = t3.^2.*z.*-3.070223042589902+t6.^2.*z.*3.070223042589902+t2.*t3.*t4.*z.*1.432770753208621e1+t2.*t3.*t5.*z.*4.298312259625863e1+t2.*t4.*t6.*z.*2.149156129812932e2-t3.*t4.*t5.*z.*2.149156129812932e2-t2.*t5.*t6.*z.*4.298312259625863e1-t4.*t5.*t6.*z.*1.432770753208621e1;
