function out1 = sharm_C_4_4(x,y,z)
%SHARM_C_4_4
%    OUT1 = SHARM_C_4_4(X,Y,Z)

%    This function was generated by the Symbolic Math Toolbox version 6.3.
%    09-Jan-2017 14:53:17

t2 = x.^2;
t3 = y.^2;
out1 = t2.*t3.*-4.437059837324712+t2.^2.*7.39509972887452e-1+t3.^2.*7.39509972887452e-1;
