function out1 = sharm_C_9_9(x,y,z)
%SHARM_C_9_9
%    OUT1 = SHARM_C_9_9(X,Y,Z)

%    This function was generated by the Symbolic Math Toolbox version 6.3.
%    09-Jan-2017 14:54:05

t2 = x.^2;
t3 = y.^2;
t4 = t3.^2;
t5 = t2.^2;
t6 = t5.^2;
out1 = t6.*x.*6.090493921755237e-1+t4.^2.*x.*5.481444529579714+t4.*t5.*x.*7.674022341411599e1-t2.*t3.*t4.*x.*5.116014894274399e1-t2.*t3.*t5.*x.*2.192577811831885e1;
