function out1 = sharm_C_7_6(x,y,z)
%SHARM_C_7_6
%    OUT1 = SHARM_C_7_6(X,Y,Z)

%    This function was generated by the Symbolic Math Toolbox version 6.3.
%    09-Jan-2017 14:53:41

t2 = x.^2;
t3 = t2.^2;
t4 = y.^2;
t5 = t4.^2;
out1 = t2.*t3.*z.*2.421824596249695+t2.*t5.*z.*3.632736894374543e1-t3.*t4.*z.*3.632736894374543e1-t4.*t5.*z.*2.421824596249695;
