function out1 = sharm_C_7_5(x,y,z)
%SHARM_C_7_5
%    OUT1 = SHARM_C_7_5(X,Y,Z)

%    This function was generated by the Symbolic Math Toolbox version 6.3.
%    09-Jan-2017 14:53:39

t2 = x.^2;
t3 = y.^2;
t4 = t2.^2;
t5 = t3.^2;
t6 = z.^2;
out1 = t2.*t4.*x.*-4.749588797990833e-1+t2.*t5.*x.*2.374794398995416+t3.*t4.*x.*4.274629918191749-t3.*t5.*x.*2.374794398995416+t4.*t6.*x.*5.699506557588999+t5.*t6.*x.*2.8497532787945e1-t2.*t3.*t6.*x.*5.699506557588999e1;
