function out1 = sharm_C_2_0(x,y,z)
%SHARM_C_2_0
%    OUT1 = SHARM_C_2_0(X,Y,Z)

%    This function was generated by the Symbolic Math Toolbox version 6.3.
%    09-Jan-2017 14:53:08

out1 = x.^2.*-5.0e-1-y.^2.*5.0e-1+z.^2;
