function out1 = sharm_S_4_4(x,y,z)
%SHARM_S_4_4
%    OUT1 = SHARM_S_4_4(X,Y,Z)

%    This function was generated by the Symbolic Math Toolbox version 6.3.
%    09-Jan-2017 14:53:18

t2 = y.^2;
t3 = x.^2;
out1 = t2.*x.*y.*-2.958039891549808+t3.*x.*y.*2.958039891549808;
