function out1 = sharm_C_5_4(x,y,z)
%SHARM_C_5_4
%    OUT1 = SHARM_C_5_4(X,Y,Z)

%    This function was generated by the Symbolic Math Toolbox version 6.3.
%    09-Jan-2017 14:53:23

t2 = x.^2;
t3 = y.^2;
out1 = t2.^2.*z.*2.218529918662356+t3.^2.*z.*2.218529918662356-t2.*t3.*z.*1.331117951197414e1;
