function out1 = sharm_S_8_4(x,y,z)
%SHARM_S_8_4
%    OUT1 = SHARM_S_8_4(X,Y,Z)

%    This function was generated by the Symbolic Math Toolbox version 6.3.
%    09-Jan-2017 14:53:48

t2 = x.^2;
t3 = y.^2;
t4 = t3.^2;
t5 = t2.^2;
t6 = z.^2;
t7 = t6.^2;
out1 = t2.*t4.*x.*y.*-1.645305822636023+t2.*t5.*x.*y.*1.645305822636023-t3.*t4.*x.*y.*1.645305822636023+t3.*t5.*x.*y.*1.645305822636023+t2.*t7.*x.*y.*6.581223290544092e1-t3.*t7.*x.*y.*6.581223290544092e1+t4.*t6.*x.*y.*3.948733974326455e1-t5.*t6.*x.*y.*3.948733974326455e1;
