function out1 = sharm_S_3_1(x,y,z)
%SHARM_S_3_1
%    OUT1 = SHARM_S_3_1(X,Y,Z)

%    This function was generated by the Symbolic Math Toolbox version 6.3.
%    09-Jan-2017 14:53:11

t2 = y.^2;
out1 = t2.*y.*-6.123724356957945e-1-x.^2.*y.*6.123724356957945e-1+y.*z.^2.*2.449489742783178;
