function coefs_to_csv( ...
	sc, ...
	ell, ...
	em, ...
	w, ...
	refradius, ...
	applied_shim, ...
	coord_geom, ...
	filename ...
	)

fid = fopen(filename,'wt');

fprintf(fid,'CS,ell,em,coef,refradius,applied_shim,coord_geom\n');

for k = 1:length(sc)
	fprintf(fid, '%s,%d,%d,%+0.6g,%f,%0.6g,%s\n', ...
		sc{k},ell(k),em(k),w(k),refradius,applied_shim,coord_geom );
end

fclose(fid);
