function coefs_to_csv_xyz( ...
	scx, ...
	ellx, ...
	emx, ...
	wx, ...
	scy, ...
	elly, ...
	emy, ...
	wy, ...
	scz, ...
	ellz, ...
	emz, ...
	wz, ...
	refradius, ...
	filename)

fid = fopen(filename,'wt');

fprintf(fid,'coil,CS,ell,em,coef,refradius\n');

for k = 1:length(scx)
	fprintf(fid, 'X,%s,%d,%d,%+0.6g,%f\n', ...
		scx{k},ellx(k),emx(k),wx(k),refradius );
end

for k = 1:length(scy)
	fprintf(fid, 'Y,%s,%d,%d,%+0.6g,%f\n', ...
		scy{k},elly(k),emy(k),wy(k),refradius );
end

for k = 1:length(scz)
	fprintf(fid, 'Z,%s,%d,%d,%+0.6g,%f\n', ...
		scz{k},ellz(k),emz(k),wz(k),refradius );
end

fclose(fid);
