function val = evaluate_sharm(sc,l,m,x,y,z,deriv)
% EVALUATE_SHARM
% Evaluates a specific solid harmonic l,m (-l<=m<=l) or its partial
% derivative at specific locations x,y,z (as from ndgrid). Calls the
% functions generated by GENERATE_SH_BASIS.
%
% Usage:
%   evaluate_sharm(sc,l,m,x,y,z,'')    gets the harmonic itself
%   evaluate_sharm(sc,l,m,x,y,z,'x')   gets the x partial derivative

switch deriv
	case ''
		base = '';
	case 'x'
		base = 'ddx_';
	case 'y'
		base = 'ddy_';
	case 'z'
		base = 'ddz_';
end

func = sprintf('%ssharm_%s_%d_%d',base,sc,l,m);

val = feval(func,x,y,z);

