function fieldfitplot(field,fit,nlfit,tag,filename)

err = fit - field;
nlerr = fit - field - nlfit;

slicepos = [1/4 1/2 3/4];
slices = [ ...
	round(size(field,3) * slicepos(1)) ...
	round(size(field,3) * slicepos(2)) ...
	round(size(field,3) * slicepos(3)) ...
];

figure;clf

%rng = max(abs(field(:)));
rng = max(abs(fit(:)));
fac = 50;
fac2 = 50;

subplot(5,3,1)
imagesc(field(:,:,slices(1))',[-rng rng])
axis equal off; colorbar
subplot(5,3,2)
imagesc(field(:,:,slices(2))',[-rng rng])
axis equal off; colorbar
title([tag ', Measured, uT / (mT/m)'])
subplot(5,3,3)
imagesc(field(:,:,slices(3))',[-rng rng])
axis equal off; colorbar

subplot(5,3,4)
imagesc(fit(:,:,slices(1))',[-rng rng])
axis equal off; colorbar
subplot(5,3,5)
imagesc(fit(:,:,slices(2))',[-rng rng])
axis equal off; colorbar
title('Fitted')
subplot(5,3,6)
imagesc(fit(:,:,slices(3))',[-rng rng])
axis equal off; colorbar

subplot(5,3,7)
imagesc(nlfit(:,:,slices(1))',[-rng rng]/fac2)
axis equal off; colorbar
subplot(5,3,8)
imagesc(nlfit(:,:,slices(2))',[-rng rng]/fac2)
axis equal off; colorbar
title('Fitted, nonlinear part only')
subplot(5,3,9)
imagesc(nlfit(:,:,slices(3))',[-rng rng]/fac2)
axis equal off; colorbar

subplot(5,3,10)
imagesc(err(:,:,slices(1))',[-rng rng]/fac)
axis equal off; colorbar
subplot(5,3,11)
imagesc(err(:,:,slices(2))',[-rng rng]/fac)
axis equal off; colorbar
title('Error')
subplot(5,3,12)
imagesc(err(:,:,slices(3))',[-rng rng]/fac)
axis equal off; colorbar

subplot(5,3,13)
imagesc(nlerr(:,:,slices(1))',[-rng rng]/fac2)
axis equal off; colorbar
subplot(5,3,14)
imagesc(nlerr(:,:,slices(2))',[-rng rng]/fac2)
axis equal off; colorbar
title('Error without nonlinear terms')
subplot(5,3,15)
imagesc(nlerr(:,:,slices(3))',[-rng rng]/fac2)
axis equal off; colorbar

drawnow

saveas(gcf,filename)


% Let's add some profiles through the image center for fit and field
xfieldprof = squeeze(field( ...
	:, ...
	round(size(field,2)/2), ...
	round(size(field,3)/2) ...
	));
yfieldprof = squeeze(field( ...
	round(size(field,1)/2), ...
	:, ...
	round(size(field,3)/2) ...
	))';
zfieldprof = squeeze(field( ...
	round(size(field,1)/2), ...
	round(size(field,2)/2), ...
	: ...
	));
xfitprof = squeeze(fit( ...
	:, ...
	round(size(fit,2)/2), ...
	round(size(fit,3)/2) ...
	));
yfitprof = squeeze(fit( ...
	round(size(fit,1)/2), ...
	:, ...
	round(size(fit,3)/2) ...
	))';
zfitprof = squeeze(fit( ...
	round(size(fit,1)/2), ...
	round(size(fit,2)/2), ...
	: ...
	));

r = 1.10 * max(abs([xfitprof; yfitprof; zfitprof]));
%r = 1.10 * max(abs([xfieldprof; yfieldprof; zfieldprof]));

figure; clf
subplot(3,2,1)
plot([xfieldprof xfitprof])
set(gca,'YLim',[-r r])
set(gca,'XLim',[0 length(xfieldprof)+1])
set(gca,'XTick',[])
title([tag ' coil, R image axis'])
%legend({'Measured' 'Fit'})
subplot(3,2,3)
plot([yfieldprof yfitprof])
set(gca,'YLim',[-r r])
set(gca,'XLim',[0 length(yfieldprof)+1])
set(gca,'XTick',[])
title([tag ' coil, A image axis'])
%legend({'Measured' 'Fit'})
subplot(3,2,5)
plot([zfieldprof zfitprof])
set(gca,'YLim',[-r r])
set(gca,'XLim',[0 length(zfieldprof)+1])
set(gca,'XTick',[])
title([tag ' coil, S image axis'])
%legend({'Measured' 'Fit'})


% Off axis profiles
xfieldprofo = squeeze(field( ...
	:, ...
	round(size(field,2)/3), ...
	round(size(field,3)/3) ...
	));
yfieldprofo = squeeze(field( ...
	round(size(field,1)/3), ...
	:, ...
	round(size(field,3)/3) ...
	))';
zfieldprofo = squeeze(field( ...
	round(size(field,1)/3), ...
	round(size(field,2)/3), ...
	: ...
	));
xfitprofo = squeeze(fit( ...
	:, ...
	round(size(fit,2)/3), ...
	round(size(fit,3)/3) ...
	));
yfitprofo = squeeze(fit( ...
	round(size(fit,1)/3), ...
	:, ...
	round(size(fit,3)/3) ...
	))';
zfitprofo = squeeze(fit( ...
	round(size(fit,1)/3), ...
	round(size(fit,2)/3), ...
	: ...
	));

subplot(3,2,2)
plot([xfieldprofo xfitprofo])
set(gca,'YLim',[-r r])
set(gca,'XLim',[0 length(xfieldprofo)+1])
set(gca,'XTick',[])
title([tag ' coil, R off-axis'])
%legend({'Measured' 'Fit'})
subplot(3,2,4)
plot([yfieldprofo yfitprofo])
set(gca,'YLim',[-r r])
set(gca,'XLim',[0 length(yfieldprofo)+1])
set(gca,'XTick',[])
title([tag ' coil, A off-axis'])
%legend({'Measured' 'Fit'})
subplot(3,2,6)
plot([zfieldprofo zfitprofo])
set(gca,'YLim',[-r r])
set(gca,'XLim',[0 length(zfieldprofo)+1])
set(gca,'XTick',[])
title([tag ' coil, S off-axis'])
%legend({'Measured' 'Fit'})


[p,n,e] = fileparts(filename);
filename2 = fullfile(p,[n '_profile' e]);
saveas(gcf,filename2)



%% Nonlinear part profiles
nlfield = field - fit + nlfit;
xnlfieldprof = squeeze(nlfield( ...
	:, ...
	round(size(nlfield,2)/2), ...
	round(size(nlfield,3)/2) ...
	));
ynlfieldprof = squeeze(nlfield( ...
	round(size(nlfield,1)/2), ...
	:, ...
	round(size(nlfield,3)/2) ...
	))';
znlfieldprof = squeeze(nlfield( ...
	round(size(nlfield,1)/2), ...
	round(size(nlfield,2)/2), ...
	: ...
	));
xnlfitprof = squeeze(nlfit( ...
	:, ...
	round(size(nlfit,2)/2), ...
	round(size(nlfit,3)/2) ...
	));
ynlfitprof = squeeze(nlfit( ...
	round(size(nlfit,1)/2), ...
	:, ...
	round(size(nlfit,3)/2) ...
	))';
znlfitprof = squeeze(nlfit( ...
	round(size(nlfit,1)/2), ...
	round(size(nlfit,2)/2), ...
	: ...
	));

r = 1.10 * max(abs([xnlfitprof; ynlfitprof; znlfitprof]));
%r = 1.10 * max(abs([xnlfieldprof; ynlfieldprof; znlfieldprof]));

figure; clf
subplot(3,2,1)
plot([xnlfieldprof xnlfitprof])
set(gca,'YLim',[-r r])
set(gca,'XLim',[0 length(xnlfieldprof)+1])
set(gca,'XTick',[])
title([tag ' coil nlfield, R axis'])
%legend({'Measured' 'Fit'})
subplot(3,2,3)
plot([ynlfieldprof ynlfitprof])
set(gca,'YLim',[-r r])
set(gca,'XLim',[0 length(ynlfieldprof)+1])
set(gca,'XTick',[])
title([tag ' coil nlfield, A axis'])
%legend({'Measured' 'Fit'})
subplot(3,2,5)
plot([znlfieldprof znlfitprof])
set(gca,'YLim',[-r r])
set(gca,'XLim',[0 length(znlfieldprof)+1])
set(gca,'XTick',[])
title([tag ' coil nlfield, S axis'])
%legend({'Measured' 'Fit'})


% Off axis profiles
xnlfieldprofo = squeeze(nlfield( ...
	:, ...
	round(size(nlfield,2)/3), ...
	round(size(nlfield,3)/3) ...
	));
ynlfieldprofo = squeeze(nlfield( ...
	round(size(nlfield,1)/3), ...
	:, ...
	round(size(nlfield,3)/3) ...
	))';
znlfieldprofo = squeeze(nlfield( ...
	round(size(nlfield,1)/3), ...
	round(size(nlfield,2)/3), ...
	: ...
	));
xnlfitprofo = squeeze(nlfit( ...
	:, ...
	round(size(nlfit,2)/3), ...
	round(size(nlfit,3)/3) ...
	));
ynlfitprofo = squeeze(nlfit( ...
	round(size(nlfit,1)/3), ...
	:, ...
	round(size(nlfit,3)/3) ...
	))';
znlfitprofo = squeeze(nlfit( ...
	round(size(nlfit,1)/3), ...
	round(size(nlfit,2)/3), ...
	: ...
	));

subplot(3,2,2)
plot([xnlfieldprofo xnlfitprofo])
set(gca,'YLim',[-r r])
set(gca,'XLim',[0 length(xnlfieldprofo)+1])
set(gca,'XTick',[])
title([tag ' coil nlfield, R off-axis'])
%legend({'Measured' 'Fit'})
subplot(3,2,4)
plot([ynlfieldprofo ynlfitprofo])
set(gca,'YLim',[-r r])
set(gca,'XLim',[0 length(ynlfieldprofo)+1])
set(gca,'XTick',[])
title([tag ' coil nlfield, A off-axis'])
%legend({'Measured' 'Fit'})
subplot(3,2,6)
plot([znlfieldprofo znlfitprofo])
set(gca,'YLim',[-r r])
set(gca,'XLim',[0 length(znlfieldprofo)+1])
set(gca,'XTick',[])
title([tag ' coil nlfield, S off-axis'])
%legend({'Measured' 'Fit'})


[p,n,e] = fileparts(filename);
filename2 = fullfile(p,[n '_nlprofile' e]);
saveas(gcf,filename2)



%% 2D profiles because why not

field(field(:)==0) = nan;
fit(isnan(field(:))) = nan;

xfieldprof2 = squeeze(field( ...
	round(size(field,1)/2), ...
	:, ...
	: ...
	));
yfieldprof2 = squeeze(field( ...
	:, ...
	round(size(field,2)/2), ...
	: ...
	))';
zfieldprof2 = squeeze(field( ...
	:, ...
	:, ...
	round(size(field,3)/2) ...
	));
xfitprof2 = squeeze(fit( ...
	round(size(fit,1)/2), ...
	:, ...
	: ...
	));
yfitprof2 = squeeze(fit( ...
	:, ...
	round(size(fit,2)/2), ...
	: ...
	))';
zfitprof2 = squeeze(fit( ...
	:, ...
	:, ...
	round(size(fit,3)/2) ...
	));

xfieldprof2o = squeeze(field( ...
	round(size(field,1)/3), ...
	:, ...
	: ...
	));
yfieldprof2o = squeeze(field( ...
	:, ...
	round(size(field,2)/3), ...
	: ...
	))';
zfieldprof2o = squeeze(field( ...
	:, ...
	:, ...
	round(size(field,3)/3) ...
	));
xfitprof2o = squeeze(fit( ...
	round(size(fit,1)/3), ...
	:, ...
	: ...
	));
yfitprof2o = squeeze(fit( ...
	:, ...
	round(size(fit,2)/3), ...
	: ...
	))';
zfitprof2o = squeeze(fit( ...
	:, ...
	:, ...
	round(size(fit,3)/3) ...
	));


r = 1.1 * max(abs([xfitprof2(:); yfitprof2(:); zfitprof2(:)]));
%r = 1.1 * max(abs([xfieldprof2(:); yfieldprof2(:); zfieldprof2(:)]));

figure; clf

subplot(2,3,1)
m1 = mesh(xfieldprof2);
colormap( [1 0 0; 0 0 1] );
set(m1,'CData',0*ones(size(get(m1,'CData'))))
hold on
m2 = mesh(xfitprof2);
set(m2,'CData',1*ones(size(get(m2,'CData'))))
title([tag ' coil, R axis'])
set(gca,'ZLim',[-r r])

subplot(2,3,2)
m1 = mesh(yfieldprof2);
colormap( [1 0 0; 0 0 1] );
set(m1,'CData',0*ones(size(get(m1,'CData'))))
hold on
m2 = mesh(yfitprof2);
set(m2,'CData',1*ones(size(get(m2,'CData'))))
title([tag ' coil, A axis'])
set(gca,'ZLim',[-r r])

subplot(2,3,3)
m1 = mesh(zfieldprof2);
colormap( [1 0 0; 0 0 1] );
set(m1,'CData',0*ones(size(get(m1,'CData'))))
hold on
m2 = mesh(zfitprof2);
set(m2,'CData',1*ones(size(get(m2,'CData'))))
title([tag ' coil, S axis'])
set(gca,'ZLim',[-r r])


subplot(2,3,4)
m1 = mesh(xfieldprof2o);
colormap( [1 0 0; 0 0 1] );
set(m1,'CData',0*ones(size(get(m1,'CData'))))
hold on
m2 = mesh(xfitprof2o);
set(m2,'CData',1*ones(size(get(m2,'CData'))))
title([tag ' coil, R off-axis'])
set(gca,'ZLim',[-r r])

subplot(2,3,5)
m1 = mesh(yfieldprof2o);
colormap( [1 0 0; 0 0 1] );
set(m1,'CData',0*ones(size(get(m1,'CData'))))
hold on
m2 = mesh(yfitprof2o);
set(m2,'CData',1*ones(size(get(m2,'CData'))))
title([tag ' coil, A off-axis'])
set(gca,'ZLim',[-r r])

subplot(2,3,6)
m1 = mesh(zfieldprof2o);
colormap( [1 0 0; 0 0 1] );
set(m1,'CData',0*ones(size(get(m1,'CData'))))
hold on
m2 = mesh(zfitprof2o);
set(m2,'CData',1*ones(size(get(m2,'CData'))))
title([tag ' coil, S off-axis'])
set(gca,'ZLim',[-r r])

drawnow


