function fieldmaps_to_gradtensor(varargin)

% Parse inputs (defaults specified here)
P = inputParser;
addOptional(P,'fieldmap_hz_0_file','/INPUTS/B0_0_Hz.nii.gz');
addOptional(P,'fieldmap_hz_x_file','/INPUTS/B0_X_Hz.nii.gz');
addOptional(P,'fieldmap_hz_y_file','/INPUTS/B0_Y_Hz.nii.gz');
addOptional(P,'fieldmap_hz_z_file','/INPUTS/B0_Z_Hz.nii.gz');
addOptional(P,'sh_order',3);
addOptional(P,'symmetry','sym');
addOptional(P,'coord_geom','Philips_headfirst_supine');
addOptional(P,'image_radius',135);
addOptional(P,'out_dir','/OUTPUTS');
parse(P,varargin{:});

% Default coordinate scaling (affects scaling of solid harmonic coefficients)
refradius = 250;

% Compute the gradient coil tensor image L
 estimate_coefs_from_fieldmaps(...
	out_dir, ...
	fieldmap_hz_0_file, ...
	fieldmap_hz_x_file, ...
	fieldmap_hz_y_file, ...
	fieldmap_hz_z_file, ...
	sh_order, ...
	symmetry, ...
	coord_geom, ...
	refradius, ...
	image_radius ...
	);
