addpath(genpath('../external/spm_read_nii'))
addpath(genpath('../external/spm_reslice'))
addpath('sh_basis')

if 0
	fieldmaps_to_gradtensor( ...
		'fieldmap_hz_0_file','../INPUTS/B0_0_Hz.nii.gz', ...
		'fieldmap_hz_x_file','../INPUTS/B0_X_Hz.nii.gz', ...
		'fieldmap_hz_y_file','../INPUTS/B0_Y_Hz.nii.gz', ...
		'fieldmap_hz_z_file','../INPUTS/B0_Z_Hz.nii.gz', ...
		'sh_order',3, ...
		'symmetry','sym', ...
		'coord_geom','Philips_headfirst_supine', ...
		'image_radius',135, ...
		'out_dir','../OUTPUTS' ...
		);
end


apply_gradtensor_to_b( ...
	'Limg_file','../OUTPUTS/L.nii.gz', ...
	'refimg_file','../INPUTS/dti.nii.gz', ...
	'bval_file','../INPUTS/bval.txt', ...
	'bvec_file','../INPUTS/bvec.txt', ...
	'out_dir','../OUTPUTS' ...
	);


